In [1]:
from urielplus import urielplus
import numpy as np
import pandas as pd

In [2]:
uriel = urielplus.URIELPlus()
uriel.integrate_databases()
uriel.set_aggregation('U')
uriel.aggregate()
#uriel.softimpute_imputation()

2025-06-30 14:59:08,956 - root - INFO - Importing all databases....
2025-06-30 14:59:08,957 - root - INFO - Importing updated SAPHON from "saphon_data.csv"....
2025-06-30 14:59:12,840 - root - INFO - Updated SAPHON integration complete..
2025-06-30 14:59:12,842 - root - INFO - Importing BDPROTO from "bdproto_data.csv"....
2025-06-30 14:59:12,843 - root - INFO - Converting ISO 639-3 codes to Glottocodes....
2025-06-30 14:59:13,157 - root - INFO - Conversion to Glottocodes complete.
2025-06-30 14:59:36,627 - root - INFO - BDPROTO integration complete.
2025-06-30 14:59:36,628 - root - INFO - Importing Grambank from "grambank_data.csv"....
2025-06-30 15:00:15,890 - root - INFO - Grambank integration complete.
2025-06-30 15:00:15,891 - root - INFO - Importing APiCS from "apics_data.csv"....
2025-06-30 15:00:18,062 - root - INFO - APiCS integration complete.
2025-06-30 15:00:18,063 - root - INFO - Importing eWAVE from "english_dialect_data.csv"....
2025-06-30 15:00:26,358 - root - INFO - eWAVE integration complete.
2025-06-30 15:00:26,359 - root - INFO - Final updates to feature data...
2025-06-30 15:02:09,623 - root - INFO - Final updates to feature data complete.
2025-06-30 15:02:09,625 - root - INFO - All databases integration complete.
2025-06-30 15:02:09,675 - root - INFO - Creating union of data across sources....
2025-06-30 15:02:10,899 - root - INFO - Union across sources creation complete.

array([[[-1.],
        [-1.],
        [-1.],
        ...,
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        ...,
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        ...,
        [-1.],
        [-1.],
        [-1.]],

       ...,

       [[ 1.],
        [ 0.],
        [ 0.],
        ...,
        [ 1.],
        [ 1.],
        [ 1.]],

       [[ 1.],
        [ 0.],
        [ 0.],
        ...,
        [ 1.],
        [ 1.],
        [ 1.]],

       [[ 1.],
        [ 0.],
        [ 0.],
        ...,
        [ 0.],
        [ 1.],
        [ 1.]]])

In [69]:
# Collect aggregated and imputed data
data: np.ndarray = np.squeeze(uriel.get_typological_data_array())
data.shape

(8174, 800)

In [70]:
a = uriel.get_typological_languages_array()
b = list(a)
b.sort()
for lang in b:
    print(lang)

aari1239
aasa1238
abad1241
abag1245
abai1240
aban1242
abar1238
abau1245
abaz1241
abee1242
aben1249
abid1235
abin1243
abip1241
abis1238
abkh1244
abom1238
abon1238
abor1240
abro1238
abua1244
abua1245
abui1241
abun1252
abur1243
abur1244
abuu1241
acat1239
acha1249
acha1250
ache1244
ache1245
ache1246
achi1256
achi1257
acht1238
achu1247
achu1248
acol1236
acro1239
acro1240
adab1235
adai1235
adam1238
adam1253
adan1247
adan1248
adan1251
adas1235
adel1244
adho1243
adio1239
adiv1239
adiw1235
adny1235
adon1237
adug1238
adyg1241
adze1240
aeka1244
aeky1238
aerr1238
afad1236
afar1241
afgh1239
afit1238
afri1274
afri1275
afro1254
afro1255
agar1251
agar1252
agat1236
agav1236
aghe1239
aghu1253
aghu1254
aghu1255
aghu1256
aghw1237
agii1245
agob1244
agoi1246
agta1234
agua1251
agua1252
agua1253
agun1238
agus1235
agut1237
agwa1247
ahan1243
ahan1244
aher1237
aheu1239
ahin1234
ahir1243
ahom1240
ahte1237
ahwa1235
aich1238
aigh1235
aika1237
aikl1237
aima1241
aime1238
aimo1244
ainb1238
ainu1240
ainu1251
aiom1240
airo1242
aito1238
ajab1235
ajas1235
ajaw1236
ajie1238
ajyi1238
akaa1242
akab1248
akab1249
akac1240
akaj1239
akak1251
akak1252
akak1253
akan1250
akar1243
akas1242
akaw1239
akeb1238
akee1238
akei1237
akeu1235
akha1245
akhv1239
akka1237
akka1240
akkk1240
akla1240
akla1241
akol1237
akoo1248
akoy1238
akpa1238
akpe1248
akru1241
akuk1235
akum1238
akun1241
akur1238
akwa1248
akya1234
alab1237
alab1246
alab1254
alac1244
alag1242
alag1248
alak1253
alam1246
alan1249
alap1235
alaw1244
alba1267
alba1269
alba1271
alco1235
aleg1238
alek1238
aleu1260
alge1235
alge1239
alge1240
algo1255
algo1256
alii1240
alla1247
alla1248
alng1239
aloa1235
alop1235
alor1247
alor1249
alsa1242
alse1251
alug1235
aluk1238
alum1246
alun1238
aluo1235
alur1250
alut1245
alvi1241
alya1239
amah1245
amah1246
amai1246
amal1242
amam1246
aman1265
aman1266
amap1240
amar1271
amar1272
amar1273
amar1274
amas1236
amat1238
amba1263
amba1265
amba1266
amba1267
amba1269
ambe1247
ambe1248
ambl1237
ambo1249
ambo1250
ambo1252
ambr1239
ambu1247
amda1238
amdo1237
amel1241
amer1248
amga1235
amha1245
amii1238
amis1246
amol1235
amol1236
amoo1242
ampa1238
ampa1239
amri1238
amto1250
amun1246
anaa1238
anak1240
anal1239
anam1247
anam1248
anam1249
anas1239
anat1248
anat1257
anca1236
anci1242
anci1244
anci1245
anci1248
anda1280
anda1282
anda1283
anda1284
anda1286
anda1287
ande1247
andh1242
andi1255
andi1257
ando1255
ando1256
andr1248
anei1239
anem1248
anem1249
anfi1235
anga1288
anga1290
anga1292
anga1293
anga1294
anga1316
angg1238
angg1239
angi1238
angl1239
angl1258
ango1254
ango1255
ango1257
ango1258
angu1242
anii1245
anii1246
anim1239
anim1240
anin1240
anip1235
anir1237
anja1238
anka1246
anma1239
anor1241
anse1238
ansu1237
anta1253
anta1255
anti1245
anua1242
anuf1239
anuk1239
anus1237
anut1237
anuu1241
anyi1244
anyi1245
aohe1237
aona1235
aore1237
aoua1234
apal1237
apal1255
apal1256
apal1257
apas1235
apat1240
apia1248
apin1244
apma1240
apma1241
apol1242
appa1236
apro1235
apuc1241
apur1254
aput1237
arab1267
arab1268
arag1245
arak1252
arak1254
arak1256
aral1243
aram1253
aram1259
aran1237
aran1261
aran1265
arao1248
arap1274
arap1275
araw1272
araw1273
araw1276
araw1281
arbe1236
arbo1245
arch1244
area1240
areb1238
aree1239
arem1240
areq1237
arge1236
argo1244
argu1237
arha1237
arho1237
arhu1242
arib1240
arib1241
arif1239
arig1246
arii1243
arik1262
arik1264
arik1265
arin1243
arin1244
arit1239
arma1244
arme1259
arom1237
arop1242
arop1243
aros1241
arta1239
arua1260
arua1261
arua1263
arue1240
aruo1240
arut1244
arva1236
asar1240
asas1240
asha1243
ashe1269
ashe1272
ashe1273
ashk1246
asho1236
asht1244
asil1242
asko1238
asli1243
asoa1238
assa1263
assa1266
assa1269
assi1247
asss1237
assy1241
astu1245
asue1235
asum1237
asun1235
asun1236
asur1254
asut1235
ataa1240
atak1252
atam1239
atam1240
atat1238
atay1247
atem1241
atha1247
athp1241
atii1237
atik1240
atoh1238
aton1241
aton1242
ator1244
atsa1241
atsa1242
atsu1245
atta1243
atti1239
atti1240
atzi1235
auhe1237
aulu1238
aura1243
aush1241
aush1242
aust1252
aust1253
aust1271
aust1304
aust1305
aust1307
aust1314
aust1315
auuu1241
auwe1239
auye1238
auyo1240
avac1239
avar1256
avat1244
avau1237
aves1237
avik1243
avok1242
awab1243
awac1238
awac1239
awad1243
awad1244
awak1250
awap1236
awar1248
awar1249
awbo1238
awee1242
awer1241
awet1244
awin1248
awiy1238
awji1241
awng1244
awng1245
awtu1239
awun1245
awut1241
awuu1235
awyi1241
axam1237
axiy1235
ayab1239
ayac1239
ayau1235
ayer1245
ayer1246
ayip1235
ayiw1239
ayiz1244
ayiz1245
ayma1253
ayoq1235
ayor1240
ayut1236
ayuu1242
azha1235
azhe1235
azoy1236
baan1241
baan1242
baat1238
baba1263
baba1264
baba1266
baba1267
baba1268
baba1273
babi1235
babu1240
baca1243
baca1246
bact1239
bada1257
bada1258
bada1261
bade1240
bade1248
badi1246
badi1247
badj1244
badu1237
bady1239
baeg1237
bael1237
baet1237
bafa1247
bafa1249
bafi1243
bafu1246
baga1270
baga1271
baga1272
baga1273
baga1274
baga1275
baga1276
bagh1251
bagi1244
bagi1246
bago1245
bagr1243
bagu1251
bagu1252
bagv1239
baha1256
baha1257
baha1258
baha1259
baha1260
baha1263
bahi1252
bahi1254
bahn1262
baho1237
baib1251
baii1251
baik1238
baim1244
baim1245
bain1259
bain1260
bain1261
bais1242
bais1246
baja1265
baje1238
baka1272
baka1273
baka1274
baka1277
bakh1245
baki1244
bako1249
bako1250
bakp1238
baku1263
bakw1243
bala1301
bala1302
bala1306
bala1310
bala1311
bala1314
bala1315
bala1316
bald1241
bali1245
bali1274
bali1278
bali1279
balk1252
balk1254
balo1261
balo1264
balt1257
balt1258
balt1263
balu1257
bama1249
bama1251
bamb1262
bamb1265
bamb1266
bamb1269
bamb1270
bame1260
bamu1253
bamu1254
bamu1256
bamu1257
bamw1238
bana1288
bana1292
bana1305
band1340
band1342
band1343
band1344
band1345
band1348
band1352
band1353
band1355
bang1339
bang1345
bang1347
bang1348
bang1350
bang1353
bang1354
bang1356
bang1363
bang1365
bang1368
bang1369
bani1254
bani1255
banj1239
bank1251
bank1256
bank1257
bank1258
bank1259
bann1247
bant1281
bant1286
bant1288
bant1293
baou1238
bara1357
bara1361
bara1362
bara1367
bara1369
bara1370
bara1371
bara1375
bara1376
bara1378
bara1380
bara1404
barb1242
barb1263
barb1265
barc1235
bard1255
bare1276
bare1279
barg1252
bari1241
bari1284
bari1286
bari1290
bari1297
bari1298
baro1252
baro1253
barr1247
barr1251
baru1267
baru1269
barw1243
barz1241
basa1280
basa1281
basa1282
basa1284
basa1286
basa1287
bash1263
bash1264
bask1236
basq1248
bass1258
bass1259
bass1260
bata1285
bata1288
bata1289
bata1290
bata1291
bata1292
bata1293
bata1294
bata1297
bata1298
bata1301
bata1314
bate1261
bate1262
bath1244
bath1248
bati1251
bati1253
bats1242
batu1255
batu1257
batu1258
batu1260
baty1234
baub1235
bauc1238
baur1251
baur1252
baur1253
bauu1244
bauw1240
bauz1241
bava1246
bawm1236
baya1257
bayb1234
bayg1239
baym1241
bayo1255
bayo1260
bayu1240
bazi1237
beam1240
beav1236
beba1238
bebe1248
bebe1250
bebe1252
bebi1242
bedi1235
bedj1245
bedo1237
beek1238
beel1236
beem1239
beez1238
befa1241
begb1241
beja1238
beka1241
bekw1241
bekw1242
bela1254
bela1255
bela1256
bela1260
belg1241
belh1239
beli1257
beli1258
beli1260
bell1243
bell1261
belu1239
bemb1255
bemb1257
bemb1258
bena1260
bena1262
bena1264
benc1235
bend1258
bend1260
beng1239
beng1280
beng1282
beng1286
beng1287
bent1237
bent1238
beny1237
beot1247
bepo1240
bera1259
bera1261
bera1262
berb1259
berb1260
beri1253
beri1254
berj1234
bero1242
bert1248
bert1249
besi1244
besm1235
beso1237
beta1252
beta1253
bete1261
bete1262
beti1248
beto1236
bett1235
betu1237
bezh1248
bhad1241
bhal1245
bhar1241
bhat1237
bhat1263
bhat1265
bhay1238
bhel1238
bhil1251
bhil1253
bhoj1244
bhot1235
bhun1242
biaf1240
biag1234
biak1248
bial1238
bian1251
bian1252
biao1253
biao1254
biao1256
biat1246
bibb1234
bidi1241
bidy1243
bidy1244
biem1237
bier1244
bier1246
biet1238
biga1237
biga1238
bign1238
biha1246
bijo1238
bika1251
biky1238
bila1253
bila1255
bila1257
bilb1241
bilb1242
bile1244
bili1250
bili1260
bilm1238
bilo1248
bilu1244
bilu1245
bima1247
bimi1240
bimo1239
bina1270
bina1271
bina1275
bina1277
bine1240
bini1246
binj1249
bino1237
bint1245
bint1246
binu1244
binu1245
bipi1237
bira1253
bira1254
birg1239
birh1242
biri1256
biri1259
birk1242
birr1240
birr1241
birw1238
bise1238
bish1244
bish1246
bisi1244
bisl1239
biso1243
biss1248
bisu1244
bita1251
bitt1240
bitu1242
bium1280
biwa1243
biyo1243
biyo1244
blab1237
blac1271
blaf1238
blag1240
blan1242
blis1239
boan1242
boan1243
boaz1244
bobo1254
bobo1255
bodo1266
bodo1267
bodo1269
bodo1272
bofi1238
boga1247
boga1251
bogh1241
bogu1241
boht1238
boik1241
boka1249
bokh1237
boko1261
boko1263
boko1266
boko1267
boky1238
bola1249
bola1250
bola1252
bolg1250
bolg1251
boli1236
boli1255
boli1256
bolo1261
bolo1262
bolo1263
bolo1266
bolo1268
boly1239
boma1246
bomb1261
bomb1262
bomi1238
bomk1234
bomu1247
bomw1238
bona1250
bond1245
bond1246
bond1247
bond1248
bone1254
bone1255
bong1282
bong1284
bong1285
bong1287
bong1289
bong1291
bonj1234
bonk1243
bonk1244
bont1247
book1241
boon1242
boor1242
bopa1235
bora1263
bora1271
bord1248
bore1247
borg1235
bori1243
boro1277
boro1279
boro1282
boro1283
boru1244
boru1252
bose1237
bosn1245
bosn1248
bote1238
botl1242
boto1242
boun1243
boun1245
bouy1240
bowa1234
boza1238
brag1240
brah1256
braj1242
braz1236
brek1238
brem1238
brer1240
bret1244
brib1243
brit1235
brit1243
brit1244
brok1247
brok1248
brok1249
broo1238
broo1239
brun1242
brun1245
buaa1245
bual1235
buam1238
bube1242
bubi1249
bubi1250
bude1236
budi1249
budo1241
budu1248
budu1250
budu1265
budz1238
buga1247
buga1250
bugh1239
bugi1244
bugl1243
bugu1246
buhi1243
buhi1245
buhu1237
bujh1238
buka1257
buka1261
bukh1238
buki1247
buki1248
buki1249
buks1238
buku1249
bukw1238
bula1255
bula1259
bulg1240
bulg1262
bulg1265
buli1254
buli1255
bull1247
bulo1242
bulu1251
bulu1253
buma1244
buma1247
bumb1241
bumm1238
bumt1240
buna1273
buna1275
buna1276
buna1277
buna1278
bund1253
bung1259
bung1264
bung1265
bung1268
bung1269
bung1270
bunn1240
buno1241
bunu1267
buol1237
bura1267
bura1269
bura1271
bura1276
bura1292
burd1238
bure1242
buri1258
burj1242
burm1262
burm1263
burm1264
burm1267
buru1296
buru1299
buru1301
buru1303
buru1304
buru1306
buru1307
buru1308
buru1309
buru1320
busa1251
busa1253
busa1254
busa1255
bush1247
bush1250
buso1238
buso1242
buss1239
busu1244
buta1242
butb1235
butl1235
butm1237
butu1244
buuu1244
buwa1243
buyu1238
buyu1239
bwaa1238
bwai1242
bwan1241
bwat1240
bwek1238
bwel1238
bwil1245
bwis1242
byan1241
byep1241
caac1237
cabe1245
cabi1241
caca1247
caca1249
caca1250
cacg1235
cacu1241
cadd1255
cadd1256
cafu1238
cagu1236
cahu1264
cahu1268
caja1238
caja1239
cajo1238
caju1236
caka1240
cakc1235
cakf1236
cala1258
cald1236
call1235
calo1236
calu1238
cama1250
came1252
came1254
came1256
caml1239
camp1261
camp1262
cams1241
camt1236
camu1235
cana1262
cand1248
cane1242
cani1243
caol1238
caom1238
capa1241
cape1242
capi1239
capp1239
caqu1242
cara1245
cara1270
cara1271
cara1272
cari1274
cari1275
cari1276
cari1279
carn1240
caro1242
caro1243
carp1235
carr1249
cash1251
cash1254
casi1235
casu1237
cata1241
cata1286
cauc1241
cavi1250
cayu1241
cayu1261
cayu1262
ceba1235
cebu1242
celt1247
celt1248
cemu1238
cenn1238
cent1394
cent1972
cent1973
cent1989
cent1990
cent1992
cent2004
cent2009
cent2013
cent2018
cent2041
cent2045
cent2050
cent2053
cent2058
cent2060
cent2072
cent2074
cent2084
cent2087
cent2089
cent2090
cent2091
cent2092
cent2098
cent2100
cent2101
cent2117
cent2118
cent2126
cent2127
cent2128
cent2131
cent2132
cent2133
cent2134
cent2136
cent2138
cent2140
cent2142
cent2144
cent2145
cent2150
cent2194
cent2243
cent2292
cent2314
cent2322
cerm1238
chac1249
chac1250
chac1251
chad1238
chad1240
chad1249
chad1250
chag1247
chai1253
chak1266
chak1270
chak1271
chal1267
chal1269
chal1275
cham1307
cham1309
cham1312
cham1313
cham1315
cham1318
cham1329
chan1309
chan1310
chan1313
chan1319
chan1322
chan1327
chao1238
char1269
chas1234
chau1258
chau1259
chav1241
chay1248
chay1249
chaz1235
chec1245
chee1238
chek1238
chen1255
chen1259
chen1266
chen1271
chep1243
chep1245
cher1271
cher1273
ches1238
chet1237
chew1245
chey1247
chha1249
chhi1245
chhu1238
chia1237
chia1262
chib1249
chib1270
chic1270
chic1271
chic1272
chic1273
chic1274
chic1275
chig1238
chig1239
chil1264
chil1275
chil1280
chil1282
chil1283
chim1300
chim1301
chim1302
chim1309
chim1310
chim1311
chim1312
chin1253
chin1272
chin1283
chin1286
chin1475
chin1476
chin1478
chin1483
chin1484
chip1236
chip1241
chip1261
chip1262
chiq1248
chiq1249
chiq1250
chir1283
chir1286
chit1248
chit1274
chit1275
chit1279
choa1237
choc1275
choc1276
choc1279
chod1238
chok1243
chok1245
chol1282
chol1284
chol1285
chon1284
chon1285
chon1287
chop1243
chor1273
chot1239
chra1242
chru1239
chua1250
chua1256
chug1252
chuj1250
chuk1270
chuk1271
chuk1273
chuk1274
chul1246
chum1261
chur1257
chur1258
chut1247
chuu1238
chuv1255
chuv1256
chuw1238
ciac1237
ciba1236
cici1237
cigb1235
cimb1238
cina1236
cind1241
cine1238
cint1239
cire1240
cisa1237
cish1238
cita1245
ciwo1236
cjin1234
clal1241
clas1249
clas1250
clas1251
clas1252
clas1253
clas1254
clel1238
coah1252
coas1294
coas1295
coas1301
coas1317
coat1238
coat1240
coat1241
coat1243
coat1244
coca1259
coch1272
coco1260
coco1261
coeu1236
cofa1242
cogu1240
coll1240
colo1249
colo1254
colo1256
colu1241
coma1245
coma1246
come1251
comm1246
como1258
como1259
cona1234
cond1242
cong1236
coon1239
coos1249
copa1236
copa1237
copt1239
coqu1236
cori1240
corn1251
coro1247
coro1248
cors1241
cosa1234
cost1249
cost1250
cota1241
coto1248
cowl1242
coxi1236
coya1241
coyo1236
coyu1235
cree1270
cree1272
creo1235
crim1257
croa1242
croa1245
cros1244
crow1244
cruz1243
cuaa1241
cuba1235
cuba1236
cube1242
cuib1242
culi1244
cuma1240
cuma1241
cume1234
cune1239
cunn1236
cupe1243
curr1243
cusc1236
cush1243
cutc1238
cuti1242
cuvo1236
cuya1240
cuyo1237
cwib1235
cypr1248
czec1253
czec1258
daai1236
daak1235
daan1235
daas1238
daat1234
daba1260
dabe1239
daci1234
dadi1249
dadi1250
dadi1251
daga1272
daga1275
dagb1246
dagb1248
dagi1241
dago1245
daha1245
daha1247
daho1238
daic1237
daii1240
dair1239
daiz1235
daka1243
dakk1238
dako1258
dakp1242
dale1238
dalm1243
dalo1238
dama1267
dama1268
dama1272
dama1278
damb1246
dame1241
damp1237
dana1252
dana1254
dand1238
dang1260
dang1262
dang1274
dani1246
dani1285
dann1241
dano1240
dans1240
danu1251
daon1243
daoo1238
dara1250
dara1251
dard1243
darf1239
darg1241
dari1249
dark1243
darl1242
darl1243
darm1243
daro1239
dars1235
darw1234
dass1243
dato1239
daun1234
daur1238
dava1245
dawa1242
dawe1237
dawr1236
daww1239
dayi1244
dayy1236
daza1242
daza1244
decc1239
dech1234
dedu1240
defa1248
defi1235
dega1238
dege1246
dege1247
dege1248
degg1238
dehu1237
dehw1238
dekk1240
dela1251
delo1240
dema1235
demi1242
demm1245
demt1241
dend1242
dend1243
deng1250
deng1253
deni1241
deno1239
deny1238
deor1238
dera1245
dera1248
desa1247
desi1235
dewo1238
dezf1238
dghw1239
dhai1238
dhal1245
dhan1264
dhan1270
dhao1237
dhar1247
dhar1248
dhat1238
dhim1246
dhiv1236
dhod1238
dhof1235
dhud1236
dhun1238
dhun1239
dhur1239
dhuw1249
dhuw1250
diaa1238
diba1242
dibi1240
dibo1245
dibo1247
dica1235
didi1258
dido1241
dier1241
diga1241
digo1243
diii1241
diji1241
dill1242
dima1251
dima1252
dimb1238
dime1235
dimi1244
diml1238
ding1239
dink1262
diod1237
dira1238
dira1242
diri1252
diri1253
diri1259
disa1239
dita1238
diti1235
diuw1238
diux1235
dixo1238
dizi1235
djab1234
djam1255
djam1256
djan1238
djap1238
djau1244
djaw1238
djee1236
djeo1235
djim1235
djin1251
djin1252
djin1253
djiw1240
djiw1241
dobe1238
dobu1241
doee1238
doga1238
dogh1241
dogo1294
dogo1295
dogr1250
dogr1252
dogu1235
doka1242
doko1243
dolg1241
dolp1239
doma1258
doma1260
domb1246
domi1236
domm1246
domp1238
domu1245
domu1246
dond1249
dong1285
dong1286
dong1288
dong1290
dong1293
dong1294
donn1239
doon1238
dori1246
doro1266
doro1267
dorz1235
doso1239
doty1234
dout1240
doya1240
drav1251
dren1238
drun1238
dual1243
duan1242
duau1237
dubl1239
dubu1240
dudu1240
dugu1248
dugu1249
dugw1239
duhw1236
duke1237
dulb1238
duli1241
duma1253
dumb1241
dumi1241
dump1242
dump1243
dumu1246
duna1248
dung1251
dung1252
dung1253
dung1254
dupa1235
dura1244
duri1242
duri1243
duru1236
duru1249
dusn1237
dusu1267
dusu1269
dusu1271
dutc1253
dutc1256
dutt1234
duun1241
duun1242
duup1238
duvl1242
duwa1244
duwe1237
dwan1238
dyaa1242
dyab1238
dyan1250
dyan1251
dyir1250
dyug1238
dyul1238
dzaa1238
dzal1238
dzan1238
dzao1238
dzod1238
dzon1239
dzuu1241
earl1247
east1236
east1436
east1472
east2282
east2295
east2304
east2328
east2330
east2332
east2333
east2337
east2340
east2342
east2343
east2345
east2346
east2347
east2349
east2352
east2354
east2357
east2363
east2370
east2371
east2372
east2379
east2387
east2390
east2398
east2403
east2409
east2414
east2418
east2426
east2440
east2443
east2447
east2449
east2462
east2464
east2465
east2472
east2482
east2485
east2486
east2502
east2516
east2520
east2534
east2538
east2542
east2544
east2545
east2551
east2555
east2556
east2558
east2563
east2652
east2690
east2694
east2695
east2696
east2773
east2779
east2782
east2834
east2851
east2881
ebir1243
ebla1238
ebri1238
ebug1241
ecua1243
edec1238
edei1244
edei1245
edei1246
eden1244
eder1237
edoi1239
edol1239
edom1234
edop1238
eeee1240
efai1241
efee1239
efik1245
efut1242
egaa1242
eggo1239
egyp1238
egyp1245
egyp1246
egyp1253
ehue1238
eipo1242
eiti1240
ejag1239
ejam1238
ekaj1238
ekar1243
ekii1241
ekit1246
ekpe1253
elal1235
elam1244
elem1253
elep1240
elhu1238
elip1238
elke1240
elmo1238
elna1235
elot1235
eloy1241
else1239
eluu1241
elym1237
emab1235
emae1237
emai1241
emai1242
eman1238
emba1238
embe1259
embe1260
embe1261
embe1262
embu1241
emer1243
emil1241
emil1243
emok1238
empl1237
emum1240
enap1235
enaw1238
ende1246
enga1252
enge1239
engg1245
ennn1243
enre1239
enuu1235
enwa1245
enwa1246
enya1247
epen1239
epie1238
epig1241
erav1242
erav1244
eree1241
erit1239
erok1237
erre1238
erro1240
ersu1241
ersu1242
eruw1238
erzy1239
esan1238
esee1247
esee1248
esht1238
esim1238
eska1234
eski1264
eski1265
eski1266
espe1235
esse1238
esta1236
esto1238
esto1258
esum1241
eteb1238
eten1239
eteo1236
eteo1240
ethi1238
etky1238
eton1253
eton1255
etru1241
etul1245
eude1234
evan1238
even1259
even1260
eviy1235
ewag1241
ewee1241
ewon1239
extr1243
eyak1241
ezaa1238
fada1250
faga1239
fair1238
fait1240
faiw1243
fala1241
fala1243
fali1285
fali1291
falk1236
famm1241
fana1235
fang1246
fang1248
fani1244
fant1241
fare1241
farn1234
faro1244
farw1235
fass1245
fasu1242
fata1245
fata1246
fata1247
fayu1238
fefe1239
femb1238
fern1234
fero1244
fiji1242
fiji1243
fili1244
filo1235
fina1242
finl1235
finn1310
finn1317
finn1318
fino1238
fipa1238
fira1238
fiwa1240
flin1247
foau1240
foia1236
foii1241
folo1238
foma1238
fong1243
fonn1241
food1238
fora1245
ford1242
fore1265
fore1270
fort1240
fran1260
fran1264
fran1266
fren1243
friu1240
fula1264
fuli1240
fuln1247
fumm1238
fung1245
furr1244
furu1242
futu1245
fuyu1242
fwai1237
fwee1238
fyam1238
fyer1241
gaaa1244
gaaa1245
gaam1241
gaan1243
gabr1253
gada1258
gada1262
gadd1242
gadd1244
gade1236
gade1242
gadj1243
gads1258
gafa1240
gaga1249
gaga1251
gagn1235
gagu1242
gahr1239
gaik1242
gail1235
gain1243
gala1252
gala1264
gale1257
gale1259
gali1258
gali1261
gali1262
gall1276
gall1278
galo1242
galo1243
gama1251
gamb1251
gamb1252
gami1242
gami1243
gamk1238
gamo1241
gamo1243
gamo1244
gana1267
gana1268
gana1270
gana1274
gana1277
gana1278
ganc1239
gand1255
gand1259
gane1237
gang1266
gang1267
gang1268
gang1270
gant1244
ganz1246
ganz1247
gaoo1237
gapa1238
gara1269
garh1243
gari1253
gari1256
garo1247
garr1259
garr1260
garu1246
garz1234
gata1239
gava1241
gavi1246
gawa1247
gaww1239
gayi1237
gayo1244
gazi1243
gbag1258
gban1258
gban1260
gbar1246
gbay1278
gbay1279
gbay1281
gbay1286
gbay1287
gbay1288
gbes1238
gbii1242
gbin1239
gbir1241
gbol1235
geba1237
gebe1237
geda1237
gede1246
geee1239
geez1241
geko1235
gela1261
gela1263
gela1264
geme1244
gend1249
geng1243
genn1243
gepo1234
gera1246
germ1281
germ1287
geru1240
gese1240
geya1234
ghad1239
ghan1235
ghan1242
ghan1244
ghan1245
ghan1247
ghar1239
ghay1237
gheg1238
gher1238
ghod1238
ghom1247
ghom1257
ghot1243
ghul1238
gian1241
giba1240
gida1247
giiw1236
giky1238
gila1241
gilb1244
gili1241
gily1242
gimi1242
gimi1243
gimm1241
gimn1238
ging1241
ginu1240
giny1241
gira1247
giry1241
gito1238
gitu1237
gitx1241
giyu1238
gizr1240
glar1241
glav1244
glio1241
gnau1240
goan1235
goar1239
goba1246
gobu1238
godi1239
godw1241
goem1240

In [71]:
uriel.new_distance("inventory", "wuch1236", "yuec1235")

2025-06-06 12:14:06,440 - root - INFO - In new_distance, calculated angular distance for inventory with wuch1236 and yuec1235: 0.03611922264099121 seconds

0.4797

In [72]:
vector = uriel.get_typological_data_array()
feature_labels = uriel.get_typological_features_array()
#myDict = {feature_labels[i]: vector[i] for i in range(len(feature_labels))}
#myDict
df = pd.DataFrame(vector.squeeze(), columns=feature_labels, index=uriel.get_typological_languages_array())
pd.set_option('display.max_rows', None)
df.loc["stan1290"]

S_SVO                                                                                                         1.0
S_SOV                                                                                                         0.0
S_VSO                                                                                                         0.0
S_VOS                                                                                                         0.0
S_OVS                                                                                                         0.0
S_OSV                                                                                                         0.0
S_SUBJECT_BEFORE_VERB                                                                                         1.0
S_SUBJECT_AFTER_VERB                                                                                          0.0
S_OBJECT_AFTER_VERB                                                                                           1.0
S_OBJECT_BEFORE_VERB                                                                                          0.0
S_SUBJECT_BEFORE_OBJECT                                                                                       1.0
S_SUBJECT_AFTER_OBJECT                                                                                        0.0
P_VOICE                                                                                                       1.0
P_VOICED_PLOSIVES                                                                                             1.0
P_VOICED_FRICATIVES                                                                                           1.0
P_EJECTIVES                                                                                                   0.0
P_IMPLOSIVES                                                                                                  0.0
P_GLOTTALIZED_RESONANTS                                                                                       0.0
P_UVULARS                                                                                                     1.0
P_UVULAR_STOPS                                                                                                0.0
P_UVULAR_CONTINUANTS                                                                                          1.0
P_LATERALS                                                                                                    1.0
P_LATERAL_L                                                                                                   1.0
P_LATERAL_OBSTRUENTS                                                                                          0.0
P_NASAL_VOWELS                                                                                                1.0
P_FRONT_ROUND_VOWELS                                                                                          1.0
P_BILABIALS                                                                                                   1.0
P_FRICATIVES                                                                                                  1.0
P_NASALS                                                                                                      1.0
P_LABIAL_VELARS                                                                                               1.0
P_CLICKS                                                                                                      0.0
P_TH                                                                                                          0.0
P_PHARYNGEALS                                                                                                 0.0
P_COMPLEX_ONSETS                                                                                              1.0
P_TONE                                                                                                        0.0
INV_OPEN_FRONT_UNROUNDED_VOWEL                                                                                1.0
INV_VOICED_BILABIAL_PLOSIVE                                                                                   1.0
INV_VOICED_BILABIAL_PLOSIVE_WITH_VOICED_LABIODENTAL_FRICATIVE                                                 0.0
INV_VOICED_BILABIAL_PLOSIVE_WITH_VOICED_BILABIAL_FRICATIVE                                                    0.0
INV_VOICELESS_PALATAL_PLOSIVE                                                                                 0.0
INV_VOICELESS_PALATAL_PLOSIVE_WITH_VOICELESS_PALATAL_FRICATIVE                                                0.0
INV_VOICED_ALVEOLAR_PLOSIVE                                                                                   1.0
INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_DENTAL_FRICATIVE                                                      0.0
INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_ALVEOLAR_LATERAL_FRICATIVE                                            0.0
INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_ALVEOPALATAL_FRICATIVE                                                0.0
INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_POSTALVEOLAR_FRICATIVE                                                0.0
INV_CLOSE_MID_FRONT_UNROUNDED_VOWEL                                                                           1.0
INV_VOICELESS_LABIODENTAL_FRICATIVE                                                                           1.0
INV_VOICELESS_GLOTTAL_FRICATIVE                                                                               0.0
INV_CLOSE_FRONT_UNROUNDED_VOWEL                                                                               1.0
INV_PALATAL_APPROXIMANT                                                                                       1.0
INV_VOICELESS_VELAR_PLOSIVE                                                                                   1.0
INV_VOICELESS_VELAR_PLOSIVE_WITH_VOICELESS_BILABIAL_PLOSIVE                                                   0.0
INV_VOICELESS_VELAR_PLOSIVE_WITH_VOICELESS_VELAR_FRICATIVE                                                    0.0
INV_ALVEOLAR_LATERAL_APPROXIMANT                                                                              1.0
INV_BILABIAL_NASAL                                                                                            1.0
INV_ALVEOLAR_NASAL                                                                                            1.0
INV_CLOSE_MID_BACK_UNROUNDED_VOWEL                                                                            0.0
INV_VOICELESS_BILABIAL_PLOSIVE                                                                                1.0
INV_VOICELESS_BILABIAL_PLOSIVE_WITH_VOICELESS_LABIODENTAL_FRICATIVE                                           0.0
INV_VOICELESS_BILABIAL_PLOSIVE_WITH_VOICELESS_ALVEOLAR_PLOSIVE                                                0.0
INV_VOICELESS_BILABIAL_PLOSIVE_WITH_VOICELESS_BILABIAL_FRICATIVE                                              0.0
INV_VOICELESS_UVULAR_PLOSIVE                                                                                  0.0
INV_VOICELESS_UVULAR_PLOSIVE_WITH_VOICED_UVULAR_FRICATIVE                                                     0.0
INV_ALVEOLAR_TRILL                                                                                            1.0
INV_VOICELESS_ALVEOLAR_FRICATIVE                                                                              1.0
INV_VOICELESS_ALVEOLAR_PLOSIVE                                                                                1.0
INV_VOICELESS_ALVEOLAR_PLOSIVE_WITH_VOICELESS_ALVEOLAR_FRICATIVE                                              0.0
INV_VOICELESS_ALVEOLAR_PLOSIVE_WITH_VOICELESS_ALVEOPALATAL_FRICATIVE                                          0.0
INV_VOICELESS_ALVEOLAR_PLOSIVE_WITH_VOICELESS_ALVEOLAR_LATERAL_FRICATIVE                                      0.0
INV_VOICELESS_ALVEOLAR_PLOSIVE_WITH_VOICELESS_DENTAL_FRICATIVE                                                0.0
INV_CLOSE_BACK_ROUNDED_VOWEL                                                                                  1.0
INV_VOICED_LABIODENTAL_FRICATIVE                                                                              1.0
INV_VOICED_LABIAL_VELAR_APPROXIMANT                                                                           1.0
INV_VOICELESS_VELAR_FRICATIVE                                                                                 0.0
INV_CLOSE_FRONT_ROUNDED_VOWEL                                                                                 1.0
INV_OPEN_OPEN_MID_FRONT_UNROUNDED_VOWEL                                                                       1.0
INV_VOICELESS_PALATAL_FRICATIVE                                                                               0.0
INV_VOICED_DENTAL_FRICATIVE                                                                                   0.0
INV_CLOSE_MID_FRONT_ROUNDED_VOWEL                                                                             1.0
INV_VOICELESS_PHARYNGEAL_FRICATIVE                                                                            0.0
INV_VELAR_NASAL                                                                                               1.0
INV_OPEN_MID_FRONT_ROUNDED_VOWEL                                                                              1.0
INV_OPEN_OPEN_MID_CENTRAL_UNROUNDED_VOWEL                                                                     0.0
INV_OPEN_BACK_UNROUNDED_VOWEL                                                                                 0.0
INV_OPEN_BACK_ROUNDED_VOWEL                                                                                   1.0
INV_VOICED_BILABIAL_IMPLOSIVE                                                                                 0.0
INV_OPEN_MID_BACK_ROUNDED_VOWEL                                                                               1.0
INV_VOICELESS_ALVEOPALATAL_FRICATIVE                                                                          0.0
INV_VOICED_RETROFLEX_PLOSIVE                                                                                  0.0
INV_VOICED_RETROFLEX_PLOSIVE_WITH_VOICED_RETROFLEX_FRICATIVE                                                  0.0
INV_VOICED_ALVEOLAR_IMPLOSIVE                                                                                 0.0
INV_CLOSE_MID_CENTRAL_UNROUNDED_VOWEL                                                                         0.0
INV_MID_CENTRAL_UNROUNDED_VOWEL                                                                               0.0
INV_OPEN_MID_FRONT_UNROUNDED_VOWEL                                                                            1.0
INV_OPEN_MID_CENTRAL_UNROUNDED_RHOTIC_VOWEL                                                                   0.0
INV_OPEN_MID_CENTRAL_ROUNDED_VOWEL                                                                            0.0
INV_VOICED_PALATAL_PLOSIVE                                                                                    0.0
INV_VOICED_PALATAL_PLOSIVE_WITH_VOICED_PALATAL_FRICATIVE                                                      0.0
INV_VOICED_VELAR_IMPLOSIVE                                                                                    0.0
INV_VOICED_VELAR_PLOSIVE_WITH_VOICED_BILABIAL_PLOSIVE                                                         0.0
INV_VOICED_VELAR_PLOSIVE_WITH_VOICED_VELAR_FRICATIVE                                                          0.0
INV_VOICED_UVULAR_PLOSIVE                                                                                     0.0
INV_VOICED_VELAR_FRICATIVE                                                                                    0.0
INV_VOICED_LABIAL_PALATAL_APPROXIMANT                                                                         1.0
INV_VOICED_GLOTTAL_FRICATIVE                                                                                  1.0
INV_VOICELESS_POSTALVEOLAR_VELAR_FRICATIVE                                                                    0.0
INV_CLOSE_CENTRAL_UNROUNDED_VOWEL                                                                             0.0
INV_CLOSE_CLOSE_MID_HIGH_FRONT_UNROUNDED_VOWEL                                                                0.0
INV_VOICED_VELARIZED_LATERAL_APPROXIMANT                                                                      0.0
INV_VOICELESS_ALVEOLAR_LATERAL_FRICATIVE                                                                      0.0
INV_VOICED_RETROFLEX_LATERAL_APPROXIMANT                                                                      0.0
INV_VOICED_ALVEOLAR_LATERAL_FRICATIVE                                                                         0.0
INV_CLOSE_BACK_UNROUNDED_VOWEL                                                                                0.0
INV_VELAR_APPROXIMANT                                                                                         0.0
INV_LABIODENTAL_NASAL                                                                                         0.0
INV_PALATAL_NASAL                                                                                             1.0
INV_RETROFLEX_NASAL                                                                                           0.0
INV_UVULAR_NASAL                                                                                              0.0
INV_CLOSE_MID_CENTRAL_ROUNDED_VOWEL                                                                           0.0
INV_OPEN_FRONT_ROUNDED_VOWEL                                                                                  0.0
INV_VOICELESS_BILABIAL_FRICATIVE                                                                              0.0
INV_ALVEOLAR_APPROXIMANT                                                                                      0.0
INV_VOICED_ALVEOLAR_LATERAL_FLAP                                                                              0.0
INV_RETROFLEX_APPROXIMANT                                                                                     0.0
INV_RETROFLEX_FLAP                                                                                            0.0
INV_ALVEOLAR_TAP                                                                                              0.0
INV_UVULAR_TRILL                                                                                              1.0
INV_UVULAR_APPROXIMANT                                                                                        0.0
INV_VOICELESS_RETROFLEX_FRICATIVE                                                                             0.0
INV_VOICELESS_POSTALVEOLAR_FRICATIVE                                                                          1.0
INV_VOICED_PALATAL_IMPLOSIVE                                                                                  0.0
INV_VOICELESS_RETROFLEX_PLOSIVE                                                                               0.0
INV_VOICELESS_RETROFLEX_PLOSIVE_WITH_VOICELESS_RETROFLEX_FRICATIVE                                            0.0
INV_CLOSE_CENTRAL_ROUNDED_VOWEL                                                                               0.0
INV_LABIODENTAL_APPROXIMANT                                                                                   0.0
INV_LABIODENTAL_FLAP                                                                                          0.0
INV_OPEN_MID_BACK_UNROUNDED_VOWEL                                                                             0.0
INV_VOICELESS_LABIO_VELAR_FRICATIVE                                                                           0.0
INV_PALATAL_LATERAL_APPROXIMANT                                                                               0.0
INV_CLOSE_CLOSE_MID_HIGH_FRONT_ROUNDED_VOWEL                                                                  0.0
INV_VOICED_RETROFLEX_FRICATIVE                                                                                0.0
INV_VOICED_ALVEOPALATAL_FRICATIVE                                                                             0.0
INV_VOICED_POSTALVEOLAR_FRICATIVE                                                                             1.0
INV_GLOTTAL_PLOSIVE                                                                                           0.0
INV_VOICED_PHARYNGEAL_FRICATIVE                                                                               0.0
INV_VOICED_BILABIAL_TRILL                                                                                     0.0
INV_VOICED_PALATAL_FRICATIVE                                                                                  0.0
INV_VELAR_LATERAL_APPROXIMANT                                                                                 0.0
INV_VOICED_BILABIAL_FRICATIVE                                                                                 0.0
INV_VOICELESS_DENTAL_FRICATIVE                                                                                0.0
INV_VOICED_UVULAR_FRICATIVE                                                                                   0.0
INV_PLACE_LABIAL                                                                                              1.0
INV_PLACE_PALATALIZED_LAB                                                                                     0.0
INV_PLACE_LABIOVELARIZED_LAB                                                                                  0.0
INV_PLACE_LABIOVELAR                                                                                          1.0
INV_PLACE_MANNER_LABIOVELAR_OBS                                                                               0.0
INV_PLACE_DENTAL                                                                                              1.0
INV_PLACE_LABIOVELARIZED_ALVEOLAR                                                                             0.0
INV_PLACE_ALVEOLAR                                                                                            1.0
INV_PLACE_PALATOALVEOLAR                                                                                      0.0
INV_PLACE_ALVEOPALATAL                                                                                        0.0
INV_PLACE_PALATAL                                                                                             1.0
INV_PLACE_RETROFLEX                                                                                           0.0
INV_PLACE_MANNER_RETROFLEX_OBS                                                                                0.0
INV_PLACE_VELAR                                                                                               1.0
INV_PLACE_PALATALIZED_VELAR                                                                                   1.0
INV_PLACE_LABIOVELARIZED_VELAR                                                                                1.0
INV_PLACE_UVULAR                                                                                              1.0
INV_PLACE_PHAR_EPIGLOTTAL                                                                                     0.0
INV_PLACE_GLOTTAL                                                                                             1.0
INV_PLACE_FRONT_ROUND                                                                                         1.0
INV_PLACE_NON_LOW_UNROUNDED                                                                                   1.0
INV_APICICAL_LAMIMANL                                                                                         0.0
INV_VELAR_UVULAR                                                                                              1.0

In [73]:
df["S_SVO"]

ghot1243   -1.0
alum1246   -1.0
arii1243   -1.0
amal1242   -1.0
arbe1236   -1.0
aran1261   -1.0
ambr1239   -1.0
abua1245    1.0
arif1239    0.0
anka1246   -1.0
afad1236   -1.0
anam1249   -1.0
alge1240    0.0
para1310   -1.0
east2544   -1.0
afar1241    0.0
aasa1238   -1.0
arva1236   -1.0
abau1245    0.0
solo1258   -1.0
mand1444   -1.0
amar1273   -1.0
abee1242    1.0
bank1256    1.0
amba1267   -1.0
cama1250   -1.0
west2630   -1.0
abai1240   -1.0
abag1245   -1.0
taji1248    0.0
abid1235   -1.0
akab1249   -1.0
abkh1244    0.0
lamp1242   -1.0
aban1242   -1.0
abua1244   -1.0
abon1238   -1.0
aben1249   -1.0
abaz1241    0.0
abro1238   -1.0
ambo1250    1.0
ambu1247    0.0
abur1243   -1.0
baha1259    0.0
pall1244   -1.0
inab1237   -1.0
anem1248   -1.0
abui1241    0.0
acha1250    1.0
anca1236   -1.0
giky1238   -1.0
achi1257    1.0
sain1246   -1.0
acol1236    1.0
akac1240   -1.0
akak1251   -1.0
akar1243   -1.0
meso1252    1.0
acha1249    0.0
east2403   -1.0
taiz1242    0.0
achi1256    1.0
acro1239   -1.0
acht1238   -1.0
achu1248    0.0
achu1247    1.0
hija1235    0.0
oman1239    1.0
cypr1248    0.0
ache1245   -1.0
adan1247   -1.0
adab1235    0.0
dzod1238   -1.0
adel1244   -1.0
dhof1235    0.0
ande1247   -1.0
adho1243   -1.0
bori1243    0.0
adio1239    1.0
galo1242    0.0
adan1251    0.0
abuu1241    0.0
adan1248   -1.0
adon1237   -1.0
adam1238   -1.0
adny1235   -1.0
adug1238   -1.0
amun1246   -1.0
amdo1237    0.0
adyg1241    0.0
adze1240    1.0
areb1238   -1.0
tuni1259    0.0
said1239    0.0
arge1236   -1.0
nort2666    0.0
haek1239   -1.0
ambe1247   -1.0
arem1240   -1.0
arme1259   -1.0
aerr1238   -1.0
east2379    0.0
alse1251   -1.0
akeu1235   -1.0
amba1269    0.0
amel1241    0.0
aeka1244    0.0
gulf1241    1.0
anda1283   -1.0
putu1241   -1.0
afgh1239   -1.0
afri1275   -1.0
akru1241   -1.0
nanu1240   -1.0
defa1248   -1.0
eloy1241   -1.0
tape1242   -1.0
afri1274    1.0
afro1254   -1.0
afit1238   -1.0
awut1241   -1.0
obok1239    0.0
agua1251   -1.0
legb1242    1.0
agat1236   -1.0
agar1252    0.0
anga1293    0.0
argu1237   -1.0
ango1254    0.0
ngel1238    1.0
agar1251   -1.0
argo1244   -1.0
isar1235   -1.0
femb1238   -1.0
anga1290    0.0
agut1237    1.0
tain1253   -1.0
para1320   -1.0
aghe1239    1.0
agua1253    0.0
esim1238    1.0
cent2084    0.0
agua1252    0.0
remo1247   -1.0
kahu1241   -1.0
aghu1253   -1.0
sout2905   -1.0
mtir1235   -1.0
ahan1243   -1.0
axam1237   -1.0
qima1242    0.0
aghu1255   -1.0
tiag1235   -1.0
akha1245    0.0
igoo1238    1.0
mobu1235   -1.0
ahan1244   -1.0
ahom1240   -1.0
apro1235   -1.0
ahir1243   -1.0
ashe1269    1.0
ahte1237   -1.0
aros1241    1.0
ainu1251   -1.0
ainb1238   -1.0
alng1239   -1.0
amar1272    1.0
agii1245   -1.0
anti1245   -1.0
aich1238    1.0
assy1241   -1.0
lish1245    0.0
akee1238   -1.0
aime1238   -1.0
aimo1244   -1.0
ainu1240    0.0
aito1238   -1.0
buru1307   -1.0
aima1241   -1.0
airo1242   -1.0
nata1254   -1.0
arik1264   -1.0
aari1239    0.0
aigh1235   -1.0
alii1240   -1.0
ajas1235    1.0
ajab1235    1.0
ajie1238   -1.0
anda1282   -1.0
sout3123   -1.0
jude1263   -1.0
jude1265    0.0
ajaw1236   -1.0
amri1238   -1.0
akan1250    1.0
bata1290   -1.0
mpur1239    1.0
ukpe1249   -1.0
akaw1239   -1.0
akpa1238   -1.0
anak1240   -1.0
anga1292    0.0
aiom1240   -1.0
akaj1239   -1.0
akka1240   -1.0
akla1240   -1.0
akab1248   -1.0
akur1238   -1.0
siwu1238   -1.0
akkk1240   -1.0
arak1252   -1.0
akas1242   -1.0
akol1237   -1.0
akum1238   -1.0
akhv1239   -1.0
akwa1248   -1.0
akak1252   -1.0
akak1253   -1.0
alab1237   -1.0
alag1242   -1.0
qawa1238   -1.0
alla1248   -1.0
aleu1260    0.0
aleg1238   -1.0
alaw1244   -1.0
amai1246   -1.0
alan1249   -1.0
alak1253   -1.0
alla1247   -1.0
ambl1237   -1.0
gheg1238   -1.0
lari1255   -1.0
alun1238    1.0
algo1255   -1.0
alut1245   -1.0
tosk1239    1.0
sout2694   -1.0
area1240    1.0
alab1254    0.0
amol1235   -1.0
alya1239    0.0
alur1250   -1.0
aman1266   -1.0
ambo1249   -1.0
amah1246    0.0
yane1238   -1.0
hame1242    0.0
amar1271   -1.0
amha1245    0.0
amis1246    0.0
amda1238   -1.0
amba1265    1.0
warj1242    1.0
amap1240    0.0
aman1265    0.0
amoo1242   -1.0
alam1246    0.0
amah1245   -1.0
amar1274    0.0
sout2954   -1.0
amto1250    0.0
guer1243    0.0
ambe1248   -1.0
west2763   -1.0
anma1239   -1.0
amii1238   -1.0
atam1239   -1.0
anda1286   -1.0
ando1255   -1.0
ngas1240    1.0
ansu1237   -1.0
xara1244    1.0
anim1239   -1.0
olde1238   -1.0
nend1239    0.0
andi1255   -1.0
anor1241   -1.0
goem1240    1.0
anuu1241    1.0
anal1239    0.0
obol1243    1.0
ando1256   -1.0
angi1238    0.0
jara1245    0.0
andh1242   -1.0
anse1238   -1.0
anta1253   -1.0
anua1242    1.0
deny1238   -1.0
anaa1238   -1.0
andr1248   -1.0
anyi1245    1.0
anem1249    1.0
ango1258    1.0
abom1238   -1.0
pemo1248    0.0
anda1284   -1.0
anga1294    0.0
brag1240   -1.0
ango1255   -1.0
arma1244   -1.0
anin1240    0.0
mufi1238    1.0
arho1237   -1.0
alor1247   -1.0
omie1241    0.0
bumb1241   -1.0
aore1237   -1.0
taik1255   -1.0
aton1241   -1.0
aoua1234   -1.0
ator1244   -1.0
uabm1237   -1.0
saaa1240    1.0
nort3139    1.0
suda1236    0.0
buki1249    1.0
agta1234   -1.0
ampa1239   -1.0
athp1241    0.0
apia1248   -1.0
jica1244   -1.0
kiow1264   -1.0
lipa1241   -1.0
mesc1238   -1.0
apin1244    0.0
apal1255    1.0
apma1240   -1.0
apuc1241    0.0
arop1243    1.0
arop1242   -1.0
apat1240    0.0
apur1254    1.0
alap1235   -1.0
west2615    0.0
aput1237   -1.0
apal1257    0.0
safe1240    0.0
arch1244    0.0
ampa1238   -1.0
arig1246   -1.0
atoh1238   -1.0
nort2875   -1.0
atak1252   -1.0
arha1237   -1.0
anga1316   -1.0
akun1241   -1.0
stan1318    0.0
impe1235   -1.0
arab1267    0.0
west2441    0.0
arag1245   -1.0
arhu1242    0.0
arik1262   -1.0
arap1275   -1.0
arik1265   -1.0
arab1268    0.0
mapu1245    1.0
arao1248    0.0
arap1274   -1.0
alge1239    0.0
karo1305    0.0
najd1235    1.0
arua1263   -1.0
arbo1245    0.0
araw1276    1.0
arua1261   -1.0
moro1292    1.0
egyp1253    1.0
asut1235    1.0
assi1247   -1.0
casu1237   -1.0
asas1240   -1.0
amer1248   -1.0
aust1271   -1.0
cish1238   -1.0
abis1238   -1.0
buru1308   -1.0
nsar1238    1.0
ashk1246   -1.0
asil1242   -1.0
assa1263    0.0
xing1248   -1.0
dano1240    0.0
alge1235   -1.0
aust1252   -1.0
asur1254   -1.0
ipul1238    1.0
astu1245   -1.0
toca1235    0.0
asoa1238   -1.0
aust1253   -1.0
mura1271   -1.0
yaos1235   -1.0
asss1237   -1.0
pele1245   -1.0
zaiw1241    0.0
atsa1242   -1.0
atam1240   -1.0
atem1241   -1.0
ivbi1241   -1.0
atti1239   -1.0
atik1240   -1.0
atii1237   -1.0
mtir1236   -1.0
ataa1240   -1.0
asht1244   -1.0
aton1242   -1.0
pudt1235   -1.0
aral1243   -1.0
waim1253   -1.0
gros1243   -1.0
pamp1244   -1.0
reel1238   -1.0
nort2686   -1.0
atsu1245   -1.0
arut1244   -1.0
anei1239    0.0
arta1239   -1.0
asum1237    1.0
alug1235   -1.0
waor1240    0.0
anut1237   -1.0
kxau1241   -1.0
agun1238   -1.0
aush1241    1.0
anuk1239   -1.0
awji1241   -1.0
heyo1240    1.0
aulu1238   -1.0
asun1235   -1.0
molm1235    1.0
auyo1240   -1.0
maka1315   -1.0
anus1237   -1.0
arue1240   -1.0
aust1304   -1.0
auye1238   -1.0
awyi1241    0.0
aura1243   -1.0
awiy1238    0.0
uzbe1248    0.0
avar1256    0.0
avau1237   -1.0
alvi1241   -1.0
aves1237   -1.0
avik1243    1.0
kota1280   -1.0
east2690    0.0
angg1238   -1.0
avat1244   -1.0
agav1236   -1.0
aush1242   -1.0
auuu1241    1.0
avok1242    1.0
avac1239   -1.0
awad1243    0.0
awap1236    0.0
cici1237   -1.0
awet1244   -1.0
angu1242   -1.0
awbo1238    0.0
aeky1238    0.0
awab1243   -1.0
araw1272   -1.0
awng1244    0.0
awak1250   -1.0
awer1241   -1.0
sout2941   -1.0
araw1273   -1.0
cent2118   -1.0
jair1235   -1.0
awun1245   -1.0
awar1248    0.0
eder1237   -1.0
abip1241    1.0
ayer1246   -1.0
mato1253   -1.0
yaka1272   -1.0
lowe1436   -1.0
xara1243    1.0
awar1249   -1.0
ayiz1245   -1.0
sout2996   -1.0
ayab1239   -1.0
ayer1245   -1.0
giny1241   -1.0
hadr1236    0.0
leyi1238   -1.0
akuk1235   -1.0
liby1240    0.0
nucl1667    0.0
sana1295    0.0
ayor1240    1.0
nort3142    0.0
ayip1235   -1.0
cent2142    0.0
sors1239   -1.0
bata1297   -1.0
ayuu1242   -1.0
taya1256   -1.0
maib1239    1.0
azha1235   -1.0
sout2697    0.0
east2695   -1.0
sanp1260    0.0
nort2697   -1.0
ipal1235   -1.0
west2778   -1.0
awin1248   -1.0
fair1238   -1.0
high1278    0.0
baba1268    1.0
bain1259   -1.0
badu1237   -1.0
bare1276    1.0
nuba1241   -1.0
tuki1240    1.0
baha1260    1.0
bara1367   -1.0
bash1264   -1.0
bamb1269    1.0
bali1278   -1.0
waim1255    0.0
bant1281   -1.0
bava1246    0.0
basa1284    1.0
bada1258   -1.0
veng1238    1.0
bamb1266    1.0
bamu1253    1.0
batu1258   -1.0
tune1241    0.0
baat1238   -1.0
nucl1630    0.0
bata1289    0.0
bauu1244   -1.0
bang1345   -1.0
baib1251   -1.0
bara1362   -1.0
buga1247   -1.0
baro1252   -1.0
ghom1247    1.0
baba1266    1.0
bats1242    0.0
baba1263   -1.0
unea1237   -1.0
nort2819   -1.0
west2458   -1.0
bama1251   -1.0
gira1247    0.0
bakp1238   -1.0
mbur1239   -1.0
kulu1255   -1.0
karn1252   -1.0
baba1264   -1.0
bubi1249   -1.0
befa1241   -1.0
baba1273   -1.0
cent2004    1.0
bain1260   -1.0
sout2642   -1.0
nort2860   -1.0
bame1260   -1.0
bamu1257   -1.0
baga1275   -1.0
bari1286    1.0
baou1238    1.0
bard1255    1.0
buna1275   -1.0
cent2087   -1.0
bann1247    1.0
bali1245   -1.0
kalu1248    0.0
bali1274    1.0
benc1235    0.0
babi1235   -1.0
kohu1244   -1.0
bend1260   -1.0
awad1244   -1.0
shoo1247   -1.0
bana1305   -1.0
baca1246   -1.0
bain1261   -1.0
bayo1255   -1.0
basa1286   -1.0
embe1259   -1.0
buna1276   -1.0
bade1248   -1.0
biag1234   -1.0
bong1289    1.0
baka1274    1.0
buru1301   -1.0
baii1251   -1.0
budu1248   -1.0
indo1317   -1.0
budu1265    1.0
bald1241   -1.0
moro1281   -1.0
bend1258   -1.0
bahn1262   -1.0
west2560    1.0
buru1320    1.0
boko1261   -1.0
orok1266    1.0
bodo1266   -1.0
baha1258    0.0
budo1241   -1.0
midd1357   -1.0
bade1240   -1.0
beav1236   -1.0
bebe1248   -1.0
icev1238    1.0
bedo1237   -1.0
byan1241   -1.0
bena1264   -1.0
bela1260   -1.0
bial1238    1.0
beka1241   -1.0
beja1238    0.0
bebe1252   -1.0
bela1254   -1.0
bemb1257    1.0
beng1280    0.0
beam1240   -1.0
beso1237   -1.0
beem1239   -1.0
besm1235   -1.0
guib1246   -1.0
blag1240   -1.0
dalo1238   -1.0
beta1252   -1.0
jurm1239    1.0
beli1258   -1.0
bena1262    1.0
bari1284    1.0
paur1238   -1.0
nort2724    0.0
bafu1246    1.0
beta1253   -1.0
bofi1238   -1.0
busa1255   -1.0
blaf1238   -1.0
brit1235   -1.0
bafa1249   -1.0
bank1251   -1.0
band1345   -1.0
mmen1238   -1.0
buna1278   -1.0
malb1235   -1.0
beba1238   -1.0
bada1257   -1.0
bazi1237   -1.0
sout2730    1.0
balt1258    1.0
gahr1239    0.0
bond1245   -1.0
bant1293   -1.0
bagh1251   -1.0
maha1287    0.0
gwam1244   -1.0
bobo1255   -1.0
hary1238   -1.0
rath1242   -1.0
baur1251   -1.0
bang1347   -1.0
bugu1246   -1.0
gian1241   -1.0
bang1356   -1.0
bitt1240    1.0
bola1249   -1.0
baga1276   -1.0
west2368   -1.0
baga1273   -1.0
east2304   -1.0
bagr1243    0.0
bawm1236    0.0
taga1272   -1.0
bugh1239   -1.0
mbon1253   -1.0
wark1247   -1.0
bhat1265   -1.0
balk1254   -1.0
beng1287   -1.0
bang1368   -1.0
bhar1241   -1.0
bhil1251   -1.0
biga1238   -1.0
bhad1241   -1.0
bhay1238   -1.0
odia1239   -1.0
bina1277    0.0
bukh1238   -1.0
bhil1253   -1.0
bahi1252    0.0
alba1269   -1.0
bimi1240   -1.0
bath1244   -1.0
boht1238   -1.0
bhoj1244    0.0
bima1247   -1.0
tuka1249    0.0
bara1369   -1.0
buwa1243   -1.0
bhat1263    0.0
bhun1242   -1.0
baha1257   -1.0
biak1248    1.0
bhal1245   -1.0
bhel1238   -1.0
bada1261   -1.0
badi1246    0.0
biss1248   -1.0
bika1251   -1.0
bidi1241    1.0
bepo1240   -1.0
biaf1240   -1.0
bian1252    0.0
bile1244   -1.0
bimo1239    1.0
bini1246    1.0
naii1241   -1.0
bila1255    1.0
bipi1237    1.0
biso1243   -1.0
bisl1239    1.0
beri1253   -1.0
biet1238   -1.0
sout2790   -1.0
kolc1235   -1.0
bijo1238   -1.0
birh1242   -1.0
balo1261   -1.0
budz1238   -1.0
bang1339   -1.0
bari1290   -1.0
biao1254   -1.0
barz1241   -1.0
bidy1244   -1.0
bahi1254   -1.0
burj1242    0.0
kana1281   -1.0
baro1253   -1.0
bulu1253   -1.0
baje1238   -1.0
banj1239   -1.0
mids1243   -1.0
make1251   -1.0
binu1245    0.0
baja1265   -1.0
bala1302   -1.0
busu1244   -1.0
bedj1245   -1.0
bakw1243   -1.0
bana1288   -1.0
baya1257    0.0
baru1269    0.0
kyak1243   -1.0
fina1242   -1.0
baka1272    1.0
binu1244    0.0
beek1238   -1.0
bura1269   -1.0
bako1249   -1.0
baki1244   -1.0
pand1264   -1.0
brok1247    0.0
beri1254   -1.0
komc1235    1.0
buki1248   -1.0
kwaa1265   -1.0
boko1263   -1.0
baka1277    0.0
baku1263   -1.0
masb1237   -1.0
bolo1262   -1.0
buhi1245   -1.0
bekw1241   -1.0
bekw1242   -1.0
baik1238   -1.0
boky1238   -1.0
bung1269   -1.0
siks1238   -1.0
bilu1245   -1.0
bell1243    0.0
bola1252   -1.0
bala1301    1.0
buol1237   -1.0
bala1306   -1.0
kuwa1247   -1.0
boli1255    1.0
bolo1268   -1.0
paok1235    1.0
bilo1248    0.0
beli1257   -1.0
sout2912   -1.0
anii1245    1.0
blab1237   -1.0
balu1257    1.0
blan1242    1.0
bala1314   -1.0
taid1247   -1.0
bolo1261   -1.0
bala1310   -1.0
magi1241   -1.0
notr1240   -1.0
bala1315   -1.0
lame1257   -1.0
bemb1255   -1.0
biem1237   -1.0
baga1270   -1.0
lima1246   -1.0
bomk1234   -1.0
bamw1238   -1.0
kein1239    0.0
bagi1246    1.0
bote1238    0.0
ghay1237   -1.0
bomb1261   -1.0
nort2890   -1.0
bina1271   -1.0
bamb1265   -1.0
bulg1265   -1.0
bomu1247    0.0
muin1242   -1.0
bilm1238   -1.0
biao1256   -1.0
buru1306    0.0
bumm1238   -1.0
bomw1238   -1.0
baim1245   -1.0
bemb1258   -1.0
bara1378   -1.0
bone1254   -1.0
book1241   -1.0
bont1247    1.0
band1355   -1.0
bint1245   -1.0
masi1266   -1.0
beng1282   -1.0
bang1354    1.0
east2482   -1.0
bier1244   -1.0
boon1242   -1.0
bata1285   -1.0
bunu1267    0.0
bant1288   -1.0
bola1250   -1.0
bant1286   -1.0
butm1237   -1.0
bund1253   -1.0
bent1237   -1.0
bone1255   -1.0
bisi1244   -1.0
bang1350   -1.0
bint1246   -1.0
beez1238   -1.0
bora1263    0.0
awee1242   -1.0
tibe1272    0.0
mund1328   -1.0
bolo1266   -1.0
bama1249   -1.0
boma1246   -1.0
barb1263    0.0
anja1238    0.0
bonj1234   -1.0
nucl1695    1.0
bero1242    1.0
bine1240    0.0
tiem1235   -1.0
bonk1244   -1.0
boga1247   -1.0
boro1282    0.0
bosn1245    1.0
bong1285    1.0
bond1247   -1.0
tuwu1238   -1.0
rema1238   -1.0
buam1238    1.0
bodo1272   -1.0
tiey1235   -1.0
daka1243   -1.0
barb1242   -1.0
band1343   -1.0
bong1287   -1.0
botl1242   -1.0
bagu1252   -1.0
binj1249   -1.0
orow1242   -1.0
broo1238   -1.0
biyo1244   -1.0
dzao1238   -1.0
anas1239   -1.0
kaur1271    0.0
band1353    1.0
koro1310    0.0
sara1326    0.0
barr1247   -1.0
bong1291    0.0
bian1251   -1.0
bopa1235   -1.0
paly1238   -1.0
bish1244    0.0
bilb1242   -1.0
tchu1241   -1.0
bagu1251   -1.0
boko1266    0.0
bung1259   -1.0
baga1271   -1.0
bago1245   -1.0
baim1244    0.0
bakh1245   -1.0
band1340    1.0
band1342   -1.0
bila1257   -1.0
wumb1241   -1.0
bulg1240   -1.0
balo1264   -1.0
busa1253    0.0
biri1259    0.0
buru1304   -1.0
bosn1248   -1.0
bamu1254   -1.0
bogu1241   -1.0
begb1241   -1.0
buru1299   -1.0
baan1242   -1.0
beng1239   -1.0
baka1273   -1.0
braj1242   -1.0
lave1249    1.0
berb1259    1.0
bara1357    0.0
bret1244    1.0
bera1259   -1.0
baur1253    0.0
brah1256   -1.0
mokp1239    1.0
bier1246   -1.0
birk1242   -1.0
birw1238   -1.0
bara1361    1.0
boru1252    0.0
brok1249   -1.0
bara1375   -1.0
brer1240   -1.0
bira1254   -1.0
bara1371   -1.0
bita1251   -1.0
east2332   -1.0
west2397   -1.0
bell1261   -1.0
bodo1269   -1.0
buru1309   -1.0
bilb1241   -1.0
abin1243    0.0
brun1245   -1.0
bass1258   -1.0
wush1238   -1.0
bauc1238   -1.0
bash1263   -1.0
kati1270   -1.0
bass1260   -1.0
bang1348   -1.0
buru1296    0.0
basa1280   -1.0
busa1254   -1.0
bara1380    0.0
buso1242   -1.0
baga1272    1.0
nucl1418    1.0
bass1259   -1.0
akoo1248   -1.0
bask1236    0.0
baho1237   -1.0
baga1274   -1.0
bais1246    0.0
yang1290   -1.0
saba1267   -1.0
bata1314   -1.0
bati1251   -1.0
bata1294   -1.0
gamo1241   -1.0
birg1239   -1.0
gagn1235   -1.0
biat1246   -1.0
bura1276   -1.0
baca1243    1.0
bhat1237   -1.0
bata1291   -1.0
rata1245   -1.0
irig1242   -1.0
budi1249   -1.0
bate1262   -1.0
baet1237   -1.0
bata1288   -1.0
bete1262   -1.0
batu1255   -1.0
bate1261   -1.0
butu1244   -1.0
bata1293    1.0
bobo1254   -1.0
bata1292   -1.0
buri1258    0.0
buaa1245   -1.0
bush1250    0.0
ntch1242    1.0
beot1247   -1.0
bush1247    1.0
bugi1244    1.0
youn1235    1.0
bong1284   -1.0
basa1281   -1.0
buga1250   -1.0
bulg1262    1.0
bulu1251   -1.0
sher1258   -1.0
tere1278   -1.0
buso1238   -1.0
brem1238   -1.0
boko1267    0.0
bung1270   -1.0
budu1250    1.0
bunn1240   -1.0
bubi1250   -1.0
bogh1241   -1.0
bull1247   -1.0
bukw1238   -1.0
bare1279   -1.0
bube1242    1.0
bael1237    1.0
baeg1237    1.0
bera1262    1.0
boor1242   -1.0
bonk1243   -1.0
bure1242   -1.0
bela1255   -1.0
baan1241   -1.0
buka1261   -1.0
boli1236   -1.0
bamu1256   -1.0
buna1277   -1.0
bolg1251   -1.0
buma1247   -1.0
birr1240   -1.0
bura1267    0.0
belg1241   -1.0
bati1253   -1.0
buki1247    1.0
bani1254   -1.0
boga1251   -1.0
dibo1245    1.0
bayb1234   -1.0
bauz1241    0.0
bwat1240   -1.0
namo1248   -1.0
bwil1245   -1.0
bwai1242   -1.0
bwek1238    1.0
bose1237   -1.0
barw1243   -1.0
bish1246   -1.0
bani1255   -1.0
laal1241   -1.0
bauw1240   -1.0
bwel1238   -1.0
biwa1243   -1.0
wuna1248    1.0
boro1277    0.0
mand1445   -1.0
sout2840   -1.0
bura1292   -1.0
bomb1262   -1.0
bafa1247   -1.0
buli1254    1.0
bwaa1238   -1.0
buna1273    1.0
cwib1235   -1.0
bwis1242   -1.0
baur1252   -1.0
bela1256   -1.0
mole1238   -1.0
pela1242    0.0
bira1253    0.0
bilu1244   -1.0
bang1353   -1.0
buhu1237   -1.0
pirl1238   -1.0
bayu1240   -1.0
buku1249    1.0
jalk1242   -1.0
mong1330    0.0
burd1238   -1.0
bari1241   -1.0
bebi1242   -1.0
beel1236   -1.0
russ1264   -1.0
busa1251   -1.0
chin1476   -1.0
bera1261   -1.0
bank1258   -1.0
bina1275   -1.0
bata1301    0.0
biky1238   -1.0
ubag1245   -1.0
beny1237   -1.0
pouy1238    0.0
bete1261   -1.0
bayg1239   -1.0
bujh1238    0.0
buyu1239   -1.0
bina1270   -1.0
biao1253   -1.0
bayo1260    0.0
bidy1243   -1.0
bili1260    0.0
biyo1243   -1.0
buma1244   -1.0
basa1287   -1.0
baru1267    0.0
bura1271   -1.0
bert1249   -1.0
medu1238    1.0
belh1239    0.0
qaqe1238   -1.0
bana1292   -1.0
band1352   -1.0
andi1257   -1.0
sout2920   -1.0
brib1243    0.0
jena1242   -1.0
boik1241   -1.0
babu1240   -1.0
mapo1242    1.0
bisu1244    0.0
beli1260    1.0
nica1252    1.0
boan1243   -1.0
bolo1263   -1.0
boan1242   -1.0
boza1238   -1.0
kemb1235   -1.0
buli1255   -1.0
biri1256    1.0
braz1236   -1.0
brit1244   -1.0
burm1264   -1.0
bebe1250    1.0
basa1282   -1.0
hain1253   -1.0
oban1244   -1.0
evan1238   -1.0
chor1273    0.0
gari1256    0.0
chuj1250    0.0
cadd1256   -1.0
leha1242    1.0
sout2958   -1.0
niva1238   -1.0
cahu1268   -1.0
chan1322   -1.0
kaqc1270    1.0
caro1242   -1.0
cemu1238    0.0
cham1313    0.0
chac1251   -1.0
chip1262    0.0
carn1240    0.0
gali1262    0.0
mose1249    1.0
stan1289    1.0
cavi1250    0.0
call1235   -1.0
chiq1248    1.0
cayu1261   -1.0
cani1243   -1.0
cabi1241   -1.0
cara1272   -1.0
cari1279    0.0
chip1236   -1.0
chim1309   -1.0
cagu1236   -1.0
chac1249    0.0
edec1238   -1.0
chav1241    1.0
bual1235    0.0
nyah1250    1.0
izor1238   -1.0
cuba1236   -1.0
cash1251    0.0
cash1254    0.0
chay1248    0.0
cand1248    0.0
cacu1241    0.0
kina1252   -1.0
cara1245   -1.0
cauc1241   -1.0
cham1318   -1.0
cafu1238   -1.0
chop1243   -1.0
samb1311   -1.0
atsa1241   -1.0
kasa1248   -1.0
cutc1238   -1.0
mala1482   -1.0
coma1246    0.0
chak1266   -1.0
caca1247   -1.0
chon1285   -1.0
chen1255   -1.0
chir1283   -1.0
cham1329   -1.0
cham1307    0.0
chod1238   -1.0
chur1258    0.0
chep1245    0.0
chau1259    0.0
mind1253   -1.0
cind1241   -1.0
chad1238   -1.0
chad1240   -1.0
koda1236   -1.0
lowe1427   -1.0
cebu1242    0.0
cham1315   -1.0
east2779    0.0
cenn1238   -1.0
czec1258    1.0
cent2045   -1.0
diji1241   -1.0
cara1270   -1.0
como1258   -1.0
fala1243    0.0
chan1319   -1.0
kaga1256    0.0
chig1238    1.0
choc1275   -1.0
cham1312    1.0
chib1270    0.0
cata1286    0.0
high1242   -1.0
chec1245    0.0
taba1266    1.0
chag1247   -1.0
chin1286    1.0
ojit1237   -1.0
chuu1238   -1.0
cahu1264    0.0
mari1278   -1.0

In [74]:
for i in list(uriel.get_typological_features_array()):
    print(i)

S_SVO
S_SOV
S_VSO
S_VOS
S_OVS
S_OSV
S_SUBJECT_BEFORE_VERB
S_SUBJECT_AFTER_VERB
S_OBJECT_AFTER_VERB
S_OBJECT_BEFORE_VERB
S_SUBJECT_BEFORE_OBJECT
S_SUBJECT_AFTER_OBJECT
P_VOICE
P_VOICED_PLOSIVES
P_VOICED_FRICATIVES
P_EJECTIVES
P_IMPLOSIVES
P_GLOTTALIZED_RESONANTS
P_UVULARS
P_UVULAR_STOPS
P_UVULAR_CONTINUANTS
P_LATERALS
P_LATERAL_L
P_LATERAL_OBSTRUENTS
P_NASAL_VOWELS
P_FRONT_ROUND_VOWELS
P_BILABIALS
P_FRICATIVES
P_NASALS
P_LABIAL_VELARS
P_CLICKS
P_TH
P_PHARYNGEALS
P_COMPLEX_ONSETS
P_TONE
INV_OPEN_FRONT_UNROUNDED_VOWEL
INV_VOICED_BILABIAL_PLOSIVE
INV_VOICED_BILABIAL_PLOSIVE_WITH_VOICED_LABIODENTAL_FRICATIVE
INV_VOICED_BILABIAL_PLOSIVE_WITH_VOICED_BILABIAL_FRICATIVE
INV_VOICELESS_PALATAL_PLOSIVE
INV_VOICELESS_PALATAL_PLOSIVE_WITH_VOICELESS_PALATAL_FRICATIVE
INV_VOICED_ALVEOLAR_PLOSIVE
INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_DENTAL_FRICATIVE
INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_ALVEOLAR_LATERAL_FRICATIVE
INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_ALVEOPALATAL_FRICATIVE
INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_POSTALVEOLAR_FRICATIVE
INV_CLOSE_MID_FRONT_UNROUNDED_VOWEL
INV_VOICELESS_LABIODENTAL_FRICATIVE
INV_VOICELESS_GLOTTAL_FRICATIVE
INV_CLOSE_FRONT_UNROUNDED_VOWEL
INV_PALATAL_APPROXIMANT
INV_VOICELESS_VELAR_PLOSIVE
INV_VOICELESS_VELAR_PLOSIVE_WITH_VOICELESS_BILABIAL_PLOSIVE
INV_VOICELESS_VELAR_PLOSIVE_WITH_VOICELESS_VELAR_FRICATIVE
INV_ALVEOLAR_LATERAL_APPROXIMANT
INV_BILABIAL_NASAL
INV_ALVEOLAR_NASAL
INV_CLOSE_MID_BACK_UNROUNDED_VOWEL
INV_VOICELESS_BILABIAL_PLOSIVE
INV_VOICELESS_BILABIAL_PLOSIVE_WITH_VOICELESS_LABIODENTAL_FRICATIVE
INV_VOICELESS_BILABIAL_PLOSIVE_WITH_VOICELESS_ALVEOLAR_PLOSIVE
INV_VOICELESS_BILABIAL_PLOSIVE_WITH_VOICELESS_BILABIAL_FRICATIVE
INV_VOICELESS_UVULAR_PLOSIVE
INV_VOICELESS_UVULAR_PLOSIVE_WITH_VOICED_UVULAR_FRICATIVE
INV_ALVEOLAR_TRILL
INV_VOICELESS_ALVEOLAR_FRICATIVE
INV_VOICELESS_ALVEOLAR_PLOSIVE
INV_VOICELESS_ALVEOLAR_PLOSIVE_WITH_VOICELESS_ALVEOLAR_FRICATIVE
INV_VOICELESS_ALVEOLAR_PLOSIVE_WITH_VOICELESS_ALVEOPALATAL_FRICATIVE
INV_VOICELESS_ALVEOLAR_PLOSIVE_WITH_VOICELESS_ALVEOLAR_LATERAL_FRICATIVE
INV_VOICELESS_ALVEOLAR_PLOSIVE_WITH_VOICELESS_DENTAL_FRICATIVE
INV_CLOSE_BACK_ROUNDED_VOWEL
INV_VOICED_LABIODENTAL_FRICATIVE
INV_VOICED_LABIAL_VELAR_APPROXIMANT
INV_VOICELESS_VELAR_FRICATIVE
INV_CLOSE_FRONT_ROUNDED_VOWEL
INV_OPEN_OPEN_MID_FRONT_UNROUNDED_VOWEL
INV_VOICELESS_PALATAL_FRICATIVE
INV_VOICED_DENTAL_FRICATIVE
INV_CLOSE_MID_FRONT_ROUNDED_VOWEL
INV_VOICELESS_PHARYNGEAL_FRICATIVE
INV_VELAR_NASAL
INV_OPEN_MID_FRONT_ROUNDED_VOWEL
INV_OPEN_OPEN_MID_CENTRAL_UNROUNDED_VOWEL
INV_OPEN_BACK_UNROUNDED_VOWEL
INV_OPEN_BACK_ROUNDED_VOWEL
INV_VOICED_BILABIAL_IMPLOSIVE
INV_OPEN_MID_BACK_ROUNDED_VOWEL
INV_VOICELESS_ALVEOPALATAL_FRICATIVE
INV_VOICED_RETROFLEX_PLOSIVE
INV_VOICED_RETROFLEX_PLOSIVE_WITH_VOICED_RETROFLEX_FRICATIVE
INV_VOICED_ALVEOLAR_IMPLOSIVE
INV_CLOSE_MID_CENTRAL_UNROUNDED_VOWEL
INV_MID_CENTRAL_UNROUNDED_VOWEL
INV_OPEN_MID_FRONT_UNROUNDED_VOWEL
INV_OPEN_MID_CENTRAL_UNROUNDED_RHOTIC_VOWEL
INV_OPEN_MID_CENTRAL_ROUNDED_VOWEL
INV_VOICED_PALATAL_PLOSIVE
INV_VOICED_PALATAL_PLOSIVE_WITH_VOICED_PALATAL_FRICATIVE
INV_VOICED_VELAR_IMPLOSIVE
INV_VOICED_VELAR_PLOSIVE_WITH_VOICED_BILABIAL_PLOSIVE
INV_VOICED_VELAR_PLOSIVE_WITH_VOICED_VELAR_FRICATIVE
INV_VOICED_UVULAR_PLOSIVE
INV_VOICED_VELAR_FRICATIVE
INV_VOICED_LABIAL_PALATAL_APPROXIMANT
INV_VOICED_GLOTTAL_FRICATIVE
INV_VOICELESS_POSTALVEOLAR_VELAR_FRICATIVE
INV_CLOSE_CENTRAL_UNROUNDED_VOWEL
INV_CLOSE_CLOSE_MID_HIGH_FRONT_UNROUNDED_VOWEL
INV_VOICED_VELARIZED_LATERAL_APPROXIMANT
INV_VOICELESS_ALVEOLAR_LATERAL_FRICATIVE
INV_VOICED_RETROFLEX_LATERAL_APPROXIMANT
INV_VOICED_ALVEOLAR_LATERAL_FRICATIVE
INV_CLOSE_BACK_UNROUNDED_VOWEL
INV_VELAR_APPROXIMANT
INV_LABIODENTAL_NASAL
INV_PALATAL_NASAL
INV_RETROFLEX_NASAL
INV_UVULAR_NASAL
INV_CLOSE_MID_CENTRAL_ROUNDED_VOWEL
INV_OPEN_FRONT_ROUNDED_VOWEL
INV_VOICELESS_BILABIAL_FRICATIVE
INV_ALVEOLAR_APPROXIMANT
INV_VOICED_ALVEOLAR_LATERAL_FLAP
INV_RETROFLEX_APPROXIMANT
INV_RETROFLEX_FLAP
INV_ALVEOLAR_TAP
INV_UVULAR_TRILL
INV_UVULAR_APPROXIMANT
INV_VOICELESS_RETROFLEX_FRICATIVE
INV_VOICELESS_POSTALVEOLAR_FRICATIVE
INV_VOICED_PALATAL_IMPLOSIVE
INV_VOICELESS_RETROFLEX_PLOSIVE
INV_VOICELESS_RETROFLEX_PLOSIVE_WITH_VOICELESS_RETROFLEX_FRICATIVE
INV_CLOSE_CENTRAL_ROUNDED_VOWEL
INV_LABIODENTAL_APPROXIMANT
INV_LABIODENTAL_FLAP
INV_OPEN_MID_BACK_UNROUNDED_VOWEL
INV_VOICELESS_LABIO_VELAR_FRICATIVE
INV_PALATAL_LATERAL_APPROXIMANT
INV_CLOSE_CLOSE_MID_HIGH_FRONT_ROUNDED_VOWEL
INV_VOICED_RETROFLEX_FRICATIVE
INV_VOICED_ALVEOPALATAL_FRICATIVE
INV_VOICED_POSTALVEOLAR_FRICATIVE
INV_GLOTTAL_PLOSIVE
INV_VOICED_PHARYNGEAL_FRICATIVE
INV_VOICED_BILABIAL_TRILL
INV_VOICED_PALATAL_FRICATIVE
INV_VELAR_LATERAL_APPROXIMANT
INV_VOICED_BILABIAL_FRICATIVE
INV_VOICELESS_DENTAL_FRICATIVE
INV_VOICED_UVULAR_FRICATIVE
INV_PLACE_LABIAL
INV_PLACE_PALATALIZED_LAB
INV_PLACE_LABIOVELARIZED_LAB
INV_PLACE_LABIOVELAR
INV_PLACE_MANNER_LABIOVELAR_OBS
INV_PLACE_DENTAL
INV_PLACE_LABIOVELARIZED_ALVEOLAR
INV_PLACE_ALVEOLAR
INV_PLACE_PALATOALVEOLAR
INV_PLACE_ALVEOPALATAL
INV_PLACE_PALATAL
INV_PLACE_RETROFLEX
INV_PLACE_MANNER_RETROFLEX_OBS
INV_PLACE_VELAR
INV_PLACE_PALATALIZED_VELAR
INV_PLACE_LABIOVELARIZED_VELAR
INV_PLACE_UVULAR
INV_PLACE_PHAR_EPIGLOTTAL
INV_PLACE_GLOTTAL
INV_PLACE_FRONT_ROUND
INV_PLACE_NON_LOW_UNROUNDED
INV_APICICAL_LAMIMANL
INV_VELAR_UVULAR
INV_NASAL_MINUS_NASAL
INV_TENSE_MINUS_TENSE
INV_ROUND_MINUS_ROUND
INV_HI_MINUS_HI
INV_LO_MINUS_LO
INV_VOWEL_3
INV_VOWEL_4
INV_VOWEL_5
INV_VOWEL_6
INV_VOWEL_7
INV_VOW_8
INV_VOW_9
INV_VOW_10_MORE
INV_CONS_ASP
INV_OBS_VD_VLESS
INV_CONT_VD_VLESS
INV_SON_VD_VLESS
INV_VOW_VD_VLESS
S_GENDER_MARK
S_SEX_MARK
S_DEFINITE_AFFIX
S_DEFINITE_WORD
S_INDEFINITE_AFFIX
S_INDEFINITE_WORD
S_POSSESSIVE_PREFIX
S_POSSESSIVE_SUFFIX
S_ADPOSITION_BEFORE_NOUN
S_ADPOSITION_AFTER_NOUN
S_POSSESSOR_BEFORE_NOUN
S_POSSESSOR_AFTER_NOUN
S_ADJECTIVE_BEFORE_NOUN
S_ADJECTIVE_AFTER_NOUN
S_DEMONSTRATIVE_WORD_BEFORE_NOUN
S_DEMONSTRATIVE_WORD_AFTER_NOUN
S_DEMONSTRATIVE_PREFIX
S_DEMONSTRATIVE_SUFFIX
S_NUMERAL_BEFORE_NOUN
S_NUMERAL_AFTER_NOUN
S_RELATIVE_BEFORE_NOUN
S_RELATIVE_AFTER_NOUN
S_RELATIVE_AROUND_NOUN
S_NOMINATIVE_VS_ACCUSATIVE_MARK
S_ERGATIVE_VS_ABSOLUTIVE_MARK
S_NEGATIVE_WORD_BEFORE_VERB
S_NEGATIVE_PREFIX
S_NEGATIVE_WORD_AFTER_VERB
S_NEGATIVE_SUFFIX
S_NEGATIVE_WORD_BEFORE_SUBJECT
S_NEGATIVE_WORD_AFTER_SUBJECT
S_NEGATIVE_WORD_BEFORE_OBJECT
S_NEGATIVE_WORD_AFTER_OBJECT
S_NEGATIVE_WORD_INITIAL
S_NEGATIVE_WORD_FINAL
S_NEGATIVE_WORD_ADJACENT_BEFORE_VERB
S_NEGATIVE_WORD_ADJACENT_AFTER_VERB
S_PLURAL_PREFIX
S_PLURAL_SUFFIX
S_PLURAL_WORD
P_VELAR_NASAL
P_VELAR_NASAL_INITIAL
S_OBJECT_HEADMARK
S_OBJECT_DEPMARK
S_POSSESSIVE_HEADMARK
S_POSSESSIVE_DEPMARK
S_TEND_HEADMARK
S_TEND_DEPMARK
S_TEND_PREFIX
S_TEND_SUFFIX
S_ANY_REDUP
S_CASE_PREFIX
S_CASE_SUFFIX
S_CASE_PROCLITIC
S_CASE_ENCLITIC
S_CASE_MARK
S_COMITATIVE_VS_INSTRUMENTAL_MARK
S_NUMCLASS_MARK
S_ADJECTIVE_WITHOUT_NOUN
S_PERFECTIVE_VS_IMPERFECTIVE_MARK
S_PAST_VS_PRESENT_MARK
S_FUTURE_AFFIX
S_TAM_PREFIX
S_TAM_SUFFIX
S_DEGREE_WORD_BEFORE_ADJECTIVE
S_DEGREE_WORD_AFTER_ADJECTIVE
S_POLARQ_MARK_INITIAL
S_POLARQ_MARK_FINAL
S_POLARQ_MARK_SECOND
S_POLARQ_WORD
S_POLARQ_AFFIX
S_SUBORDINATOR_WORD_BEFORE_CLAUSE
S_SUBORDINATOR_WORD_AFTER_CLAUSE
S_SUBORDINATOR_SUFFIX
S_PROSUBJECT_WORD
S_PROSUBJECT_AFFIX
S_PROSUBJECT_CLITIC
S_NEGATIVE_AFFIX
S_NEGATIVE_WORD
S_ANY_AGREEMENT_ON_ADJECTIVES
S_COMPLEMENTIZER_WORD_BEFORE_CLAUSE
S_COMPLEMENTIZER_WORD_AFTER_CLAUSE
S_VOX
S_XVO
S_XOV
S_OXV
S_OVX
S_OBLIQUE_AFTER_VERB
S_OBLIQUE_AFTER_OBJECT
S_OBLIQUE_BEFORE_VERB
S_OBLIQUE_BEFORE_OBJECT
S_ARTICLE_WORD_BEFORE_NOUN
S_ARTICLE_WORD_AFTER_NOUN
P_CODAS
P_COMPLEX_CODAS
P_LONG_VOWELS
S_DEFINITE_ARTICLE
S_INDEFINITE_ARTICLE
S_ARTICLE_BEFORE_NOUN
S_ARTICLE_AFTER_NOUN
S_NOM_CONJ_COM_EXP_DIFF
S_INCL_EXCL_DIST
S_3RD_PERSON_GENDER_DIST
S_DUAL_UNIT_PRON
S_DEMO_DIS_CONTR_3_MORE
S_DEMO_ELEV_DIST
S_DEMO_VIS_NONVIS_DIST
S_DEMOCLASS_MARK
M_NONPHONO_NUM_ALLO
M_SUPPL_NUM_NOUNS_3_MORE
M_PROD_SING_MARK
M_PROD_DUAL_MARK
M_PROD_PLURAL_MARK
M_ASSOC_PLURAL_MARK
M_PROD_NOUN_DERIVATION
M_PROD_AGENT_DERIVATION
M_PROD_OBJ_DERIVATION
S_SHAPE_MARK
S_ANIMACY_MARK
S_PLANT_MARK
S_POSSClASS_MARK
S_DIFF_POSS_ALIEN_INALIEN_NOUN
M_ADJ_AS_VERBS_PRED
M_ADJ_ATTRIB_VERB_MORPH
M_MORPH_CASE_CORE_ARGS
M_MORPH_CASE_PRON_CORE
M_MORPH_CASE_OBL_NP
M_MORPH_CASE_OBL_PRON
M_PROD_INFIX_VERBS
M_PRESENT_MARK
M_PAST_MARK
M_FUTURE_MARK
M_INTRANS_SUFFIX_INDEX
M_INTRANS_PREFIX_INDEX
M_TRANS_AGENT_SUFFIX_INDEX
M_TRANS_AGENT_PREFIX_INDEX
M_TRANS_PATIENT_SUFFIX_INDEX
M_TRANS_PATIENT_PREFIX_INDEX
M_TAM_DIST_MARK_VAR
M_VERB_CLASS_MARK_VAR
M_PERSON_DIST_MARK_VAR
M_VERB_STEM_PERSON
M_VERB_BENEF_APPLIC_MARK
M_VERB_INSTR_APPLIC_MARK
S_DITR_RECIP_PATIENT_MARK
M_NEGATION_VERB_MARK
M_DIR_LOC_VERB_MARK
M_VERB_SUPPL_PART_NUM
M_VERB_SUPPL_TA
M_CONJ_CLASS
M_INTRANS_TO_TRANS_AFFIX
M_PHON_BIND_REFLEXIVE
M_PHON_BIND_RECIPROCAL
M_VERB_CLASS_ABS
S_COPULA_PRED_NOM
S_SERIAL_VERB_CONSTR
S_MOOD_AUX_MARK
S_ASPECT_AUX_MARK
S_TENSE_AUX_MARK
S_REG_VERB_COMPOUND
S_VERB_ADJUNCT_CONSTR
S_NOUN_INCORP_INTRANS
S_EXISTENTIAL_VERB
S_POSTURE_VERBS_LOCATUM
S_SMALL_VERB_ROOTS
S_VERB_INIT_TRANS
S_VERB_MED_TRANS
S_VERB_FINAL_TRANS
S_CONST_ORDER_MAIN_SUB
S_CLAUSAL_NOMINAL_OBJ_POS
S_FIXED_CORE_ARG_ORDER
M_CLAUSE_FINAL_NEG
M_CLAUSE_INIT_NEG
S_IMPERATIVE_DECLARATIVE_NEG
S_SAME_NEG_PREDICATION
S_CONTROL_UNCONTROL_PRED
M_MORPH_PASSIVE_VERB
M_MORPH_ANTIPASSIVE_VERB
M_MORPH_INVERSE_VERB
S_CLAUSE_CHAINING
M_SWITCH_REF_MARKER
M_MORPH_SIM_SEQ_CLAUSES
M_CAUSATIVE_AFFIX_CLITIC
S_CAUSATIVE_SAY_VERB
M_PROD_TRIAL_MARK_NOUN
M_PROD_PAUCAL_MARK_NOUN
S_LOGOPHORIC_PRON
S_ANY_AGREEMENT_ON_ADNOMINAL_DEMONSTRATIVES
S_ANY_AGREEMENT_ON_ARTICLES
S_VERB_ANIMACY_MARKER
M_PROD_DIMINUTIVE_NOUN
M_PROD_AUGMENTATIVE_NOUN
M_PHONO_GENDER_SYSTEM
M_2ND_PERSON_GENDER_DIST
M_1ST_PERSON_GENDER_DIST
M_ANY_AGREEMENT_ON_ADNOMINAL_NUMERALS
S_UQ_BEFORE_NOUN
S_UQ_AFTER_NOUN
S_ALL_EVERY_QUANT_DIFF
S_PRED_POSSESS_HABEO
S_S-LIKE_LOCATIVE_POSSESS
S_S-LIKE_DATIVE_POSSESS
S_S-LIKE_ADNOMINAL_POSSESS
S_S-LIKE_COMITATIVE_POSSESS
S_INTONATION_ONLY_POLAR
S_WORD_ORDER_POLAR_INTERROG
S_COMPARATIVE_SURPASS_FORM
S_COMPARATIVE_LOCATIVE_MARKER
S_CONJOINED_CLAUSES_COMPARATIVE
S_COMPARATIVE_NEUTRAL_MARKER
S_BOUND_COMPARATIVE_MARKER
S_NON_BOUND_COMPARATIVE_MARKER
S_PARTICLE_AND_VERBAL_POLAR
S_VERBAL_MORPHOLOGY_POLAR
S_TONAL_POLAR_INTERROG
M_IDEOPHONES_BEYOND_SOUND
S_V_NOT_V_POLAR
S_AUXILIARY_NEGATION
S_PARTICLE_NEGATION
M_GIVE_VERB_SUPPLETION
S_INCLUSORY_CONSTRUCTION
S_FREE_PASSIVE_MARKER
S_FREE_ANTIPASSIVE_MARKER
S_AGENT_IN_PASSIVE
S_INDEPENDENT_REFLEXIVE_PRONOUN
S_INDEPENDENT_RECIPROCAL_PRONOUN
S_MULTIPLE_TENSES_BY_DISTANCE
M_MOOD_MORPHOLOGY_VERB
S_IRREGULAR_ADNOMINAL_POSSESSIVES
M_AUGMENTATIVE_GENDER_CLASS_SHIFT
M_DIMINUTIVE_GENDER_CLASS_SHIFT
S_SINGULAR_FREE_MARKER
S_DUAL_FREE_MARKER
S_PLURAL_FREE_MARKER
S_TRIAL_FREE_MARKER
S_PAUCAL_FREE_MARKER
M_UNPREDICTABLE_GENDER_CLASS
S_DIRECT_EVIDENCE_MARKING
S_INDIRECT_EVIDENCE_MARKING
S_CONTENT_INTERROG_VERB
S_COUNT_MASS_INTERROG_QUANT
S_CONTENT_INTERROG_IN_SITU
S_INTERNALLY_HEADED_RELATIVE
S_CORRELATIVE_RELATIVE
S_ADJOINED_RELATIVE
M_DECIMAL_NUMERAL_SYSTEM
M_QUINARY_NUMERAL_EVIDENCE
M_VIGESIMAL_NUMERAL_EVIDENCE
M_BODY_PART_TALLYING_SYSTEM
M_PERSON_CATEGORY_NEUTRALIZATION
S_PATIENT_LABILE_VERBS
M_SEE_VERB_SUPPLETION
M_COME_VERB_SUPPLETION
S_ACCUSATIVE_ALIGNMENT_FLAGGING
S_ERGATIVE_ALIGNMENT_FLAGGING
S_NEUTRAL_ALIGNMENT_FLAGGING
M_POLITENESS_2ND_PERSON
S_PREPOSED_CCOMP_THINKING
S_POSTPOSED_CCOMP_THINKING
M_PREFIX_POSSESSED_NOUN
M_SUFFIX_POSSESSED_NOUN
M_MOOD_AUX_PARTICLE
M_ASPECT_AUX_PARTICLE
M_TENSE_AUX_PARTICLE
S_PRO_DROP_VERB_OR_ARGUMENT
S_VAO
S_AOV
S_AVO
S_OVA
S_OAV
S_VOA
S_INTERROGATIVE_PHRASE_INITIAL
M_SYNCRETISM
S_COMPOUND_INTERROGATIVES
S_PROCONJ_SING
M_INDEFINITE_GENERIC
S_PLURAL_MARK
M_PLURAL_MARK_3RD_PLURAL_PRON_DIST
M_ANTIDUAL
S_DEMONSTRATIVE_DEFINITE_CO-OCCUR
S_DEMONSTRATIVE_SAME_FORM
M_DIST_NUMERAL_MARK
M_ORDINAL_NUMERALS
S_POSSESSOR_AFTER_NOUN.1
S_POSSESSOR_BEFORE_NOUN.1
M_COMP_ADJ_MARK
M_COMP_STAN_MARK
S_MTA
S_TAM
S_TMA
S_TAM_MARK
M_PROGRESSIVE_MARK
S_PROGRESSIVE_MARK_EXTENDED_USE
S_HABITUAL_MARK_EXTENDED_USE
M_MIX_AT_SYS
S_SAME_TAM_MARK_NEG_CLAUSE
S_STATIVE_PRES_PERF_DYNAMIC_MARK
S_INCHOATIVE_MEANING_ASPECT_MARK
S_VERB_CHAIN_ASPECT_CHANGE
S_ABILITY_VERB_EPISTEMIC_POSSIBILITY
S_GIVE_DOUBLE_OBJ_CONSTR
S_OthTR
S_OthRT
S_VTR
S_VRT
S_SRTV
S_STRV
S_SVTR
S_SVRT
S_PRONOMIAL_SUBJ_OBLIG_PRON_WORDS
S_EXPL_SUBJ_SEEM
S_EXPL_SUBJ_EXIST
S_CONSTR_RAIN_FALLS
S_HEADACHE_BODY_PART_SUBJ
S_HEADACHE_EXP_SUBJ
S_LIKE_EXP_SUBJ
S_BODY_PART_SUBJ
S_EXP_SUBJ_FEAR_VERBAL
S_INSTRUMENTAL_ADPOSITION
S_NOUN_CONJ_COM_DIFF
S_NOM_VERB_CONJ_DIFF
S_COPULA_PRED_NOUN
S_COPULA_PRED_ADJ
S_COPULA_PRED_LOC
S_PRED_NOUN_LOCATION_DIFF
S_TRANS_POSS_VERB_EXIST_DIFF
S_MOTION_TO_FROM_DIFF
S_PUSH_AT_REST_MARK
S_PULL_AT_REST_MARK
S_COME_GO_DIRECTIONAL
S_TAKE_SERIAL
S_GIVE_SERIAL
S_INTENS_REFLEX_DIFF
S_RECIP_REFLEX_CONSTR_ID
S_SPECIAL_RECIP_CONSTR
S_TYPICAL_PASSIVE_CONSTRUCTION
S_APPLICATIVE_CONSTRUCTION
S_SUBJECT_RELATIVE_ZERO
S_SUBJECT_RELATIVE_PARTICLE
S_OBJECT_RELATIVE_ZERO
S_OBJECT_RELATIVE_PARTICLE
S_INSTRUMENT_RELATIVE_ZERO
S_INSTRUMENT_RELATIVE_PARTICLE
S_SPEAK_COMPLEMENTIZER_RELATED_TO_SAY
S_KNOW_COMPLEMENTIZER_RELATED_TO_SAY
S_WANT_COMPLEMENT_IMPLICIT_SUBJECT
S_THINK_WANT_COMPLEMENTIZER
S_VERB_DOUBLING_TEMP
S_NEGATIVE_AFTER_VERB
S_NEGATIVE_BEFORE_VERB
S_BIPARTITE_NEGATION
S_INDEF_PRON_COOCCUR_PRED_NEG
S_FRONTING_PARTICLE
S_CLEF_FOCUS_PARTICLE
S_CLEF_COPULA_FOCUS
S_VERB_DOUBLING
S_ALSO_FOLLOW_FOCUS
S_ALSO_PRECEDE_FOCUS
S_OP_VOCATIVE_MARKER_AFTER_NOUN
S_OP_VOCATIVE_MARKER_BEFORE_NOUN
P_PARA_CLICKS_AFFECTIVE
S_MONOMORPHEMIC_WORD_TEARS
S_HAND_ARM_DIST
S_FINGER_TOE_DIST
S_BODY_HAIR_FEATHER_DIST
S_HEAR_SMELL_DIST
S_GREEN_BLUE_DIST
INV_VOWEL_HEIGHT_5
INV_VOWEL_HEIGHT_4
INV_VOWEL_HEIGHT_3
INV_VOWEL_HEIGHT_2
INV_VOICED_ALVEOLAR_FRICATIVE
P_PRENASALIZED_SEGMENTS
S_SHE/HER_USED_FOR_INANIMATE_REFERENTS
S_HE/HIM_USED_FOR_INANIMATE_REFERENTS
S_ALTERNATIVE_FORMS/PHRASES_FOR_REFERENTIAL_(NON-DUMMY)_IT
S_ALTERNATIVE_FORMS/PHRASES_FOR_DUMMY_IT
S_GENERALIZED_THIRD_PERSON_SINGULAR_PRONOUN:_SUBJECT_PRONOUNS
S_GENERALIZED_THIRD_PERSON_SINGULAR_PRONOUN:_OBJECT_PRONOUNS
S_ME_INSTEAD_OF_I_IN_COORDINATE_SUBJECTS
S_MYSELF/MESELF_INSTEAD_OF_I_IN_COORDINATE_SUBJECTS
S_BENEFACTIVE_“PERSONAL_DATIVE”_CONSTRUCTION
M_NO_GENDER_DISTINCTION_IN_THIRD_PERSON_SINGULAR
S_REGULARIZED_REFLEXIVES_PARADIGM
S_OBJECT_PRONOUN_FORMS_SERVING_AS_BASE_FOR_FIRST_AND/OR_SECOND_PERSON_REFLEXIVES
S_SUBJECT_PRONOUN_FORMS_SERVING_AS_BASE_FOR_REFLEXIVES
M_NO_NUMBER_DISTINCTION_IN_REFLEXIVES
S_ABSOLUTE_USE_OF_REFLEXIVES
S_EMPHATIC_REFLEXIVES_WITH_OWN
M_CREATION_OF_POSSESSIVE_PRONOUNS_WITH_PREFIX_FI-_+PERSONAL_PRONOUN
S_SUBJECT_PRONOUN_FORMS_AS_(MODIFYING)_POSSESSIVE_PRONOUNS:_FIRST_PERSON_SINGULAR
S_SUBJECT_PRONOUN_FORMS_AS_(MODIFYING)_POSSESSIVE_PRONOUNS:_FIRST_PERSON_PLURAL
S_SUBJECT_PRONOUN_FORMS_AS_(MODIFYING)_POSSESSIVE_PRONOUNS:_THIRD_PERSON_SINGULAR
S_SUBJECT_PRONOUN_FORMS_AS_(MODIFYING)_POSSESSIVE_PRONOUNS:_THIRD_PERSON_PLURAL
S_YOU_AS_(MODIFYING)_POSSESSIVE_PRONOUN
S_SECOND_PERSON_PRONOUN_FORMS_OTHER_THAN_YOU_AS_(MODIFYING)_POSSESSIVE_PRONOUN
S_OBJECT_PRONOUN_FORMS_AS_(MODIFYING)_POSSESSIVE_PRONOUNS:_THIRD_PERSON_SINGULAR
S_OBJECT_PRONOUN_FORMS_AS_(MODIFYING)_POSSESSIVE_PRONOUNS:_THIRD_PERSON_PLURAL
S_OBJECT_PRONOUN_FORMS_AS_(MODIFYING)_POSSESSIVE_PRONOUNS:_FIRST_PERSON_SINGULAR
S_OBJECT_PRONOUN_FORMS_AS_(MODIFYING)_POSSESSIVE_PRONOUNS:_FIRST_PERSON_PLURAL
S_USE_OF_US_+_NP_IN_SUBJECT_FUNCTION
S_USE_OF_US_IN_OBJECT_FUNCTION_WITH_SINGULAR_REFERENT
S_NON-COORDINATED_SUBJECT_PRONOUN_FORMS_IN_OBJECT_FUNCTION
S_NON-COORDINATED_OBJECT_PRONOUN_FORMS_IN_SUBJECT_FUNCTION
S_DISTINCTION_BETWEEN_EMPHATIC_VS._NON-EMPHATIC_FORMS_OF_PRONOUNS
M_INDEPENDENT_POSSESSIVE_PRONOUN_FORMS_WITH_ADDED_NASAL
S_FORMS_OR_PHRASES_FOR_THE_SECOND_PERSON_PLURAL_PRONOUN_OTHER_THAN_YOU
S_FORMS_OR_PHRASES_FOR_THE_SECOND_PERSON_SINGULAR_PRONOUN_OTHER_THAN_YOU
S_DISTINCT_FORMS_FOR_INCLUSIVE/EXCLUSIVE_FIRST_PERSON_NON-SINGULAR
M_MORE_NUMBER_DISTINCTIONS_IN_PERSONAL_PRONOUNS_THAN_SIMPLY_SINGULAR_VS._PLURAL
M_SPECIALIZED_PLURAL_MARKERS_FOR_PRONOUNS
M_PLURAL_FORMS_OF_INTERROGATIVE_PRONOUNS:_USING_ADDITIONAL_ELEMENTS
M_PLURAL_FORMS_OF_INTERROGATIVE_PRONOUNS:_REDUPLICATION
S_SINGULAR_IT_FOR_PLURAL_THEY_IN_ANAPHORIC_USE
S_OBJECT_PRONOUN_DROP
S_SUBJECT_PRONOUN_DROP:_REFERENTIAL_PRONOUNS
S_SUBJECT_PRONOUN_DROP:_DUMMY_PRONOUNS
S_INSERTION_OF_IT_WHERE_STE_FAVOURS_ZERO
S_DELETION_OF_IT_IN_REFERENTIAL_IT_IS-CONSTRUCTIONS
S_DELETION_OF_IT_IN_NON-REFERENTIAL_IT_IS-CONSTRUCTIONS
M_REGULARIZATION_OF_PLURAL_FORMATION:_EXTENSION_OF_-S_TO_STE_IRREGULAR_PLURALS
M_REGULARIZATION_OF_PLURAL_FORMATION:_PHONOLOGICAL_REGULARIZATION
M_PLURAL_MARKING_VIA_PREPOSED_ELEMENTS
M_PLURAL_MARKING_VIA_POSTPOSED_ELEMENTS
M_ASSOCIATIVE_PLURAL_MARKED_BY_POSTPOSED_AND_THEM/THEM_ALL/DEM
M_ASSOCIATIVE_PLURAL_MARKED_BY_OTHER_ELEMENTS
M_GROUP_PLURALS
M_DIFFERENT_COUNT/MASS_NOUN_DISTINCTIONS_RESULTING_IN_USE_OF_PLURAL_FOR_STE_SINGULAR
M_ABSENCE_OF_PLURAL_MARKING_ONLY_AFTER_QUANTIFIERS
M_PLURAL_MARKING_GENERALLY_OPTIONAL_:_FOR_NOUNS_WITH_HUMAN_REFERENTS
M_PLURAL_MARKING_GENERALLY_OPTIONAL:_FOR_NOUNS_WITH_NON-HUMAN_REFERENTS
S_DOUBLE_DETERMINERS
S_USE_OF_DEFINITE_ARTICLE_WHERE_STE_HAS_INDEFINITE_ARTICLE
S_USE_OF_INDEFINITE_ARTICLE_WHERE_STE_HAS_DEFINITE_ARTICLE
S_USE_OF_ZERO_ARTICLE_WHERE_STE_HAS_INDEFINITE_ARTICLE
S_USE_OF_DEFINITE_ARTICLE_WHERE_STE_FAVOURS_ZERO
S_USE_OF_INDEFINITE_ARTICLE_WHERE_STE_FAVOURS_ZERO
M_INDEFINITE_ARTICLE_ONE/WAN
S_DEMONSTRATIVES_FOR_DEFINITE_ARTICLES
S_THEM_INSTEAD_OF_DEMONSTRATIVE_THOSE
S_YON/YONDER_INDICATING_REMOTENESS
S_PROXIMAL_AND_DISTAL_DEMONSTRATIVES_WITH_ʼHEREʼ_AND_ʼTHEREʼ
M_NO_NUMBER_DISTINCTION_IN_DEMONSTRATIVES
M_GROUP_GENITIVES
S_EXISTENTIAL_CONSTRUCTION_TO_EXPRESS_POSSESSIVE
S_PHRASES_WITH_FOR_+_NOUN_TO_EXPRESS_POSSESSION:_FOR-PHRASE_FOLLOWING_POSSESSED_NP
S_PHRASES_WITH_FOR_+_NOUN_TO_EXPRESS_POSSESSION:_FOR-PHRASE_PRECEDING_POSSESSED_NP
S_POSTNOMINAL_PHRASES_WITH_BILONG/BLONG/LONG/BLO_TO_EXPRESS_POSSESSION
S_OMISSION_OF_GENITIVE_SUFFIX;_POSSESSION_EXPRESSED_THROUGH_BARE_JUXTAPOSITION_OF_NOUNS
S_DOUBLE_COMPARATIVES_AND_SUPERLATIVES
S_REGULARIZED_COMPARISON_STRATEGIES:_EXTENSION_OF_SYNTHETIC_MARKING
S_REGULARIZED_COMPARISON_STRATEGIES:_EXTENSION_OF_ANALYTIC_MARKING
S_MUCH_AS_COMPARATIVE_MARKER
S_AS/TO_AS_COMPARATIVE_MARKERS
S_COMPARATIVES_AND_SUPERLATIVES_OF_PARTICIPLES
S_COMPARATIVE_MARKING_ONLY_WITH_THAN
S_COMPARATIVE_MARKING_WITH_MORE…AND
S_ZERO_MARKING_OF_DEGREE
S_ATTRIBUTIVE_ADJECTIVAL_MODIFIERS_FOLLOW_HEAD_NOUN
S_WIDER_RANGE_OF_USES_OF_PROGRESSIVE_BE_+_V-ING_THAN_IN_STE:_EXTENSION_TO_STATIVE_VERBS
S_WIDER_RANGE_OF_USES_OF_PROGRESSIVE_BE_+_V-ING_THAN_IN_STE:_EXTENSION_TO_HABITUAL_CONTEXTS
S_INVARIANT_BE_AS_HABITUAL_MARKER
S_DO_AS_HABITUAL_MARKER
S_OTHER_NON-STANDARD_HABITUAL_MARKERS:_SYNTHETIC
S_OTHER_NON-STANDARD_HABITUAL_MARKERS:_ANALYTIC
S_PROGRESSIVE_MARKER_STAP_OR_STAY
S_BE_SAT/STOOD_WITH_PROGRESSIVE_MEANING
S_THERE_WITH_PAST_PARTICIPLE_IN_RESULTATIVE_CONTEXTS
S_MEDIAL_OBJECT_PERFECT
S_AFTER-PERFECT
S_LEVELLING_OF_THE_DIFFERENCE_BETWEEN_PRESENT_PERFECT_AND_SIMPLE_PAST:_SIMPLE_PAST_FOR_STE_PRESENT_PERFECT
S_LEVELLING_OF_THE_DIFFERENCE_BETWEEN_PRESENT_PERFECT_AND_SIMPLE_PAST:_PRESENT_PERFECT_FOR_STE_SIMPLE_PAST
S_SIMPLE_PRESENT_FOR_CONTINUATIVE_OR_EXPERIENTIAL_PERFECT
S_BE_AS_PERFECT_AUXILIARY
S_DO_AS_UNSTRESSED_TENSE_MARKER
S_COMPLETIVE/PERFECT_DONE
S_COMPLETIVE/PERFECT_HAVE/BE_+_DONE_+_PAST_PARTICIPLE
S_“SEQUENTIAL”_OR_“IRREALIS”_BE_DONE
S_COMPLETIVE/PERFECT_MARKER_SLAM
S_EVER_AS_MARKER_OF_EXPERIENTIAL_PERFECT
S_PERFECT_MARKER_ALREADY
S_FINISH-DERIVED_COMPLETIVE_MARKERS
S_PAST_TENSE/ANTERIOR_MARKER_BEEN
S_ANTERIOR_HAD_+_BARE_ROOT
S_LOOSENING_OF_SEQUENCE_OF_TENSES_RULE
S_GO-BASED_FUTURE_MARKERS
S_VOLITION-BASED_FUTURE_MARKERS_OTHER_THAN_WILL
S_COME-BASED_FUTURE/INGRESSIVE_MARKERS
S_PRESENT_TENSE_FORMS_FOR_NEUTRAL_FUTURE_REFERENCE
S_IS_FOR_AM/WILL_WITH_1ST_PERSON_SINGULAR
S_WOULD_FOR_(DISTANT)_FUTURE_IN_CONTRAST_TO_WILL_(IMMEDIATE_FUTURE)
S_WOULD_IN_IF-CLAUSES
S_DOUBLE_MODALS
S_EPISTEMIC_MUSTN’T
S_PRESENT_TENSE_FORMS_OF_MODALS_USED_WHERE_STE_HAS_PAST_TENSE_FORMS

In [75]:
sub = df.loc[['stan1293', 'stan1290', 'stan1295', 'mand1415', 'russ1263', 'kore1280', 'viet1252', 'mong1331', 'amha1245']]

good_feats = [col for col in sub.columns if set(sub[col].unique()) == {1., 0.}]

good_feats

['S_SVO',
 'S_SOV',
 'S_OSV',
 'S_SUBJECT_AFTER_VERB',
 'S_OBJECT_AFTER_VERB',
 'S_OBJECT_BEFORE_VERB',
 'S_SUBJECT_AFTER_OBJECT',
 'P_VOICE',
 'P_VOICED_PLOSIVES',
 'P_VOICED_FRICATIVES',
 'P_EJECTIVES',
 'P_IMPLOSIVES',
 'P_UVULARS',
 'P_UVULAR_CONTINUANTS',
 'P_FRONT_ROUND_VOWELS',
 'P_LABIAL_VELARS',
 'P_TH',
 'P_TONE',
 'INV_VOICED_BILABIAL_PLOSIVE',
 'INV_VOICELESS_PALATAL_PLOSIVE',
 'INV_VOICED_ALVEOLAR_PLOSIVE',
 'INV_VOICED_ALVEOLAR_PLOSIVE_WITH_VOICED_POSTALVEOLAR_FRICATIVE',
 'INV_CLOSE_MID_FRONT_UNROUNDED_VOWEL',
 'INV_VOICELESS_LABIODENTAL_FRICATIVE',
 'INV_VOICELESS_GLOTTAL_FRICATIVE',
 'INV_CLOSE_FRONT_UNROUNDED_VOWEL',
 'INV_CLOSE_MID_BACK_UNROUNDED_VOWEL',
 'INV_ALVEOLAR_TRILL',
 'INV_CLOSE_BACK_ROUNDED_VOWEL',
 'INV_VOICED_LABIODENTAL_FRICATIVE',
 'INV_VOICED_LABIAL_VELAR_APPROXIMANT',
 'INV_VOICELESS_VELAR_FRICATIVE',
 'INV_CLOSE_FRONT_ROUNDED_VOWEL',
 'INV_OPEN_OPEN_MID_FRONT_UNROUNDED_VOWEL',
 'INV_VOICELESS_PALATAL_FRICATIVE',
 'INV_VOICED_DENTAL_FRICATIVE',
 'INV_CLOSE_MID_FRONT_ROUNDED_VOWEL',
 'INV_VELAR_NASAL',
 'INV_OPEN_MID_FRONT_ROUNDED_VOWEL',
 'INV_OPEN_OPEN_MID_CENTRAL_UNROUNDED_VOWEL',
 'INV_OPEN_BACK_UNROUNDED_VOWEL',
 'INV_OPEN_BACK_ROUNDED_VOWEL',
 'INV_VOICED_BILABIAL_IMPLOSIVE',
 'INV_OPEN_MID_BACK_ROUNDED_VOWEL',
 'INV_VOICELESS_ALVEOPALATAL_FRICATIVE',
 'INV_VOICED_ALVEOLAR_IMPLOSIVE',
 'INV_MID_CENTRAL_UNROUNDED_VOWEL',
 'INV_OPEN_MID_FRONT_UNROUNDED_VOWEL',
 'INV_VOICED_PALATAL_PLOSIVE',
 'INV_VOICED_VELAR_FRICATIVE',
 'INV_VOICED_LABIAL_PALATAL_APPROXIMANT',
 'INV_VOICED_GLOTTAL_FRICATIVE',
 'INV_CLOSE_CENTRAL_UNROUNDED_VOWEL',
 'INV_CLOSE_CLOSE_MID_HIGH_FRONT_UNROUNDED_VOWEL',
 'INV_CLOSE_BACK_UNROUNDED_VOWEL',
 'INV_VELAR_APPROXIMANT',
 'INV_PALATAL_NASAL',
 'INV_CLOSE_MID_CENTRAL_ROUNDED_VOWEL',
 'INV_VOICELESS_BILABIAL_FRICATIVE',
 'INV_ALVEOLAR_APPROXIMANT',
 'INV_RETROFLEX_APPROXIMANT',
 'INV_ALVEOLAR_TAP',
 'INV_UVULAR_TRILL',
 'INV_VOICELESS_RETROFLEX_FRICATIVE',
 'INV_VOICELESS_POSTALVEOLAR_FRICATIVE',
 'INV_CLOSE_CENTRAL_ROUNDED_VOWEL',
 'INV_LABIODENTAL_APPROXIMANT',
 'INV_OPEN_MID_BACK_UNROUNDED_VOWEL',
 'INV_VOICELESS_LABIO_VELAR_FRICATIVE',
 'INV_CLOSE_CLOSE_MID_HIGH_FRONT_ROUNDED_VOWEL',
 'INV_VOICED_RETROFLEX_FRICATIVE',
 'INV_VOICED_POSTALVEOLAR_FRICATIVE',
 'INV_GLOTTAL_PLOSIVE',
 'INV_VOICED_BILABIAL_FRICATIVE',
 'INV_VOICELESS_DENTAL_FRICATIVE',
 'INV_VOICED_UVULAR_FRICATIVE',
 'INV_PLACE_PALATALIZED_LAB',
 'INV_PLACE_MANNER_LABIOVELAR_OBS',
 'INV_PLACE_DENTAL',
 'INV_PLACE_LABIOVELARIZED_ALVEOLAR',
 'INV_PLACE_PALATOALVEOLAR',
 'INV_PLACE_ALVEOPALATAL',
 'INV_PLACE_RETROFLEX',
 'INV_PLACE_MANNER_RETROFLEX_OBS',
 'INV_PLACE_LABIOVELARIZED_VELAR',
 'INV_PLACE_UVULAR',
 'INV_PLACE_GLOTTAL',
 'INV_PLACE_FRONT_ROUND',
 'INV_APICICAL_LAMIMANL',
 'INV_VELAR_UVULAR',
 'INV_NASAL_MINUS_NASAL',
 'INV_TENSE_MINUS_TENSE',
 'INV_ROUND_MINUS_ROUND',
 'INV_HI_MINUS_HI',
 'INV_LO_MINUS_LO',
 'INV_VOWEL_5',
 'INV_VOWEL_6',
 'INV_VOWEL_7',
 'INV_VOW_8',
 'INV_VOW_9',
 'INV_VOW_10_MORE',
 'INV_CONS_ASP',
 'INV_OBS_VD_VLESS',
 'INV_CONT_VD_VLESS',
 'INV_SON_VD_VLESS',
 'S_SEX_MARK',
 'S_POSSESSIVE_SUFFIX',
 'S_ADPOSITION_BEFORE_NOUN',
 'S_ADPOSITION_AFTER_NOUN',
 'S_POSSESSOR_BEFORE_NOUN',
 'S_POSSESSOR_AFTER_NOUN',
 'S_ADJECTIVE_BEFORE_NOUN',
 'S_ADJECTIVE_AFTER_NOUN',
 'S_DEMONSTRATIVE_WORD_BEFORE_NOUN',
 'S_DEMONSTRATIVE_WORD_AFTER_NOUN',
 'S_NUMERAL_AFTER_NOUN',
 'S_RELATIVE_BEFORE_NOUN',
 'S_RELATIVE_AFTER_NOUN',
 'S_NEGATIVE_WORD_BEFORE_VERB',
 'S_NEGATIVE_PREFIX',
 'S_NEGATIVE_WORD_AFTER_VERB',
 'S_NEGATIVE_SUFFIX',
 'S_PLURAL_SUFFIX',
 'S_PLURAL_WORD',
 'P_VELAR_NASAL',
 'P_VELAR_NASAL_INITIAL',
 'S_TEND_SUFFIX',
 'S_ANY_REDUP',
 'S_CASE_SUFFIX',
 'S_CASE_PROCLITIC',
 'S_CASE_MARK',
 'S_NUMCLASS_MARK',
 'S_PERFECTIVE_VS_IMPERFECTIVE_MARK',
 'S_PAST_VS_PRESENT_MARK',
 'S_FUTURE_AFFIX',
 'S_TAM_PREFIX',
 'S_TAM_SUFFIX',
 'S_POLARQ_MARK_INITIAL',
 'S_POLARQ_MARK_FINAL',
 'S_POLARQ_MARK_SECOND',
 'S_POLARQ_WORD',
 'S_POLARQ_AFFIX',
 'S_SUBORDINATOR_WORD_BEFORE_CLAUSE',
 'S_SUBORDINATOR_WORD_AFTER_CLAUSE',
 'S_PROSUBJECT_WORD',
 'S_PROSUBJECT_AFFIX']

In [76]:
sub

,S_SVO,S_SOV,S_VSO,S_VOS,S_OVS,S_OSV,S_SUBJECT_BEFORE_VERB,S_SUBJECT_AFTER_VERB,S_OBJECT_AFTER_VERB,S_OBJECT_BEFORE_VERB,...,S_“NEGATIVE_INVERSION”,S_INVERTED_WORD_ORDER_IN_INDIRECT_QUESTIONS,S_NO_INVERSION/NO_AUXILIARIES_IN_WH-QUESTIONS,S_NO_INVERSION/NO_AUXILIARIES_IN_MAIN_CLAUSE_YES/NO_QUESTIONS,S_DOUBLY_FILLED_COMP-POSITION_WITH_WH-WORDS,S_SUPERLATIVE_MARKER_MOST_OCCURRING_BEFORE_HEAD_NOUN,S_EITHER_ORDER_OF_OBJECTS_IN_DOUBLE_OBJECT_CONSTRUCTIONS_(IF_BOTH_OBJECTS_ARE_PRONOMINAL),S_PRESENCE_OF_SUBJECT_IN_IMPERATIVES,S_LIKE_AS_A_FOCUSSING_DEVICE,S_LIKE_AS_A_QUOTATIVE_PARTICLE
stan1293,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
stan1290,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
stan1295,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
mand1415,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
russ1263,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
kore1280,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
viet1252,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
mong1331,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
amha1245,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [77]:
sub = sub[["S_SVO",
    "S_ADPOSITION_AFTER_NOUN",
    "S_POSSESSOR_BEFORE_NOUN",
    "S_ADJECTIVE_BEFORE_NOUN",
    "P_TONE",
    "P_EJECTIVES",
    "INV_CLOSE_MID_FRONT_UNROUNDED_VOWEL",
    "INV_VELAR_NASAL",
    "INV_UVULAR_TRILL",
    "INV_VOICELESS_GLOTTAL_FRICATIVE",
]]
sub

,S_SVO,S_ADPOSITION_AFTER_NOUN,S_POSSESSOR_BEFORE_NOUN,S_ADJECTIVE_BEFORE_NOUN,P_TONE,P_EJECTIVES,INV_CLOSE_MID_FRONT_UNROUNDED_VOWEL,INV_VELAR_NASAL,INV_UVULAR_TRILL,INV_VOICELESS_GLOTTAL_FRICATIVE
stan1293,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
stan1290,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
stan1295,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
mand1415,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
russ1263,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
kore1280,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
viet1252,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
mong1331,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
amha1245,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0

In [78]:
for i in list(sub.loc['mong1331'].to_numpy()):
    print(int(i))

0
1
1
1
0
0
1
0
0
0

In [79]:
alignfreeze = df.loc[['stan1318',
'hebr1245',
'nucl1301',
'west2369',
'hind1269',
'latv1249',
'lith1251',
'czec1258',
'poli1260',
'slov1269',
'bulg1262',
'slov1268',
'russ1263',
'ukra1253',
'mode1248',
'stan1290',
'stan1288',
'stan1289',
'ital1282',
'port1283',
'roma1327',
'dani1285',
'norw1258',
'swed1254',
'stan1295',
'afri1274',
'finn1318',
'hung1274',
'mand1415',
'thai1261',
'viet1252',
'nucl1643',
'kore1280',
'tami1289']]

In [27]:
vector = uriel.get_phylogeny_data_array()
feature_labels = uriel.get_phylogeny_features_array()
df = pd.DataFrame(vector.squeeze(), columns=feature_labels, index=uriel.get_phylogeny_languages_array())

pd.set_option('display.max_rows', None)
df.loc["mand1415"]

F_Austronesian                                        0.0
F_Nuclear Austronesian                                0.0
F_Malayo-Polynesian                                   0.0
F_Central-Eastern Malayo-Polynesian                   0.0
F_Eastern Malayo-Polynesian                           0.0
F_Oceanic                                             0.0
F_Western Oceanic linkage                             0.0
F_North New Guinea linkage                            0.0
F_Huon Gulf                                           0.0
F_Markham                                             0.0
F_Ainu                                                0.0
F_Atlantic-Congo                                      0.0
F_Volta-Congo                                         0.0
F_Kwa Volta-Congo                                     0.0
F_Nyo                                                 0.0
F_Potou-Tano                                          0.0
F_Tano                                                0.0
F_Central Tano                                        0.0
F_Akanic                                              0.0
F_Muskogean                                           0.0
F_Alabaman-Koasati                                    0.0
F_Eskimo-Aleut                                        0.0
F_Mangarrayi-Maran                                    0.0
F_Maran                                               0.0
F_Indo-European                                       0.0
F_Albanian                                            0.0
F_Albanian-Tosk                                       0.0
F_Panoan                                              0.0
F_Mainline Pano                                       0.0
F_Pano Nawa                                           0.0
F_Headwaters                                          0.0
F_Arawakan                                            0.0
F_Western Maipuran                                    0.0
F_Afro-Asiatic                                        0.0
F_Semitic                                             0.0
F_West Semitic                                        0.0
F_Ethiosemitic                                        0.0
F_South Ethiopic                                      0.0
F_Transversal South Ethiopic                          0.0
F_Amharic-Argobba                                     0.0
F_Chadic                                              0.0
F_West Chadic                                         0.0
F_West Chadic A                                       0.0
F_West Chadic A.2-3                                   0.0
F_West Chadic A A.3                                   0.0
F_Pama-Nyungan                                        0.0
F_Desert Nyungic                                      0.0
F_Wati                                                0.0
F_Unclassified Wati                                   0.0
F_Nuclear-Macro-Je                                    0.0
F_Je                                                  0.0
F_Je Setentrional                                     0.0
F_Araucanian                                          0.0
F_Central Semitic                                     0.0
F_Arabian                                             0.0
F_Arabic                                              0.0
F_North African Arabic                                0.0
F_Moroccan-Andalusian Arabic                          0.0
F_Egyptic Arabic                                      0.0
F_Egypto-Sudanic Arabic                               0.0
F_Nuclear Trans New Guinea                            0.0
F_Kainantu-Goroka                                     0.0
F_Kainantu                                            0.0
F_Gauwa                                               0.0
F_Auyana                                              0.0
F_Kosena-Awiyaana                                     0.0
F_Cushitic                                            0.0
F_Central Cushitic                                    0.0
F_Aymara                                              0.0
F_Nuclear Aymara                                      0.0
F_Turkic                                              0.0
F_Common Turkic                                       0.0
F_Oghuz-Kipchak-Uyghur                                0.0
F_Oghuz                                               0.0
F_South Oghuz                                         0.0
F_Tucanoan                                            0.0
F_Eastern Tucanoan                                    0.0
F_Eastern Eastern Tucanoan                            0.0
F_Eastern Eastern Tucanoan I                          0.0
F_Bara-Tatuyo                                         0.0
F_Indo-Iranian                                        0.0
F_Indo-Aryan                                          0.0
F_Indo-Aryan Eastern zone                             0.0
F_Oriya-Gauda-Kamrupa                                 0.0
F_Gauda-Kamrupa                                       0.0
F_Gauda-Banga                                         0.0
F_Benue-Congo                                         0.0
F_Bantoid                                             0.0
F_Southern Bantoid                                    0.0
F_Narrow Bantu                                        0.0
F_Central-Western Bantu                               0.0
F_Kongo-Yaka-Suku-Hungan                              0.0
F_Celtic                                              0.0
F_Nuclear Celtic                                      0.0
F_TGB Celtic                                          0.0
F_Insular Celtic                                      0.0
F_Brythonic                                           0.0
F_Southwestern Brythonic                              0.0
F_Northwest Sumatra-Barrier Islands                   0.0
F_Toba-Batak                                          0.0
F_Northern Batak                                      0.0
F_Balto-Slavic                                        0.0
F_Slavic                                              0.0
F_South Slavic                                        0.0
F_Eastern South Slavic                                0.0
F_Macedo-Bulgarian                                    0.0
F_Bolivian Nawa                                       0.0
F_Cariban                                             0.0
F_Guianan                                             0.0
F_Barbacoan                                           0.0
F_Cayapa-Colorado                                     0.0
F_Mayan                                               0.0
F_Core Mayan                                          0.0
F_Western Mayan                                       0.0
F_Cholan-Tzeltalan                                    0.0
F_Cholan                                              0.0
F_Chol-Chontal                                        0.0
F_Athapaskan-Eyak-Tlingit                             0.0
F_Athapaskan-Eyak                                     0.0
F_Athapaskan                                          0.0
F_Northern Athapaskan                                 0.0
F_Bolgar                                              0.0
F_Malayo-Sumbawan                                     0.0
F_North and East Malayo-Sumbawan                      0.0
F_Aceh-Chamic                                         0.0
F_Chamic                                              0.0
F_Coastal Chamic                                      0.0
F_Cham                                                0.0
F_Chukotko-Kamchatkan                                 0.0
F_Chukotian                                           0.0
F_Sino-Tibetan                                        1.0
F_Sinitic                                             1.0
F_Northern Chinese                                    1.0
F_Mandarinic                                          1.0
F_Southern Maipuran                                   0.0
F_Pre-Andine                                          0.0
F_Asha-Ashe-Kak-Matsi-Nan                             0.0
F_Asha-Ashe-Kak                                       0.0
F_Asha-Ashe                                           0.0
F_Northern Maipuran                                   0.0
F_Caribbean                                           0.0
F_Island Carib-Garifuna                               0.0
F_North Volta-Congo                                   0.0
F_Gur                                                 0.0
F_Central Gur                                         0.0
F_Northern Central Gur                                0.0
F_Bwamu-Oti-Volta                                     0.0
F_Oti-Volta                                           0.0
F_Nuclear Oti-Volta                                   0.0
F_Gurma-Yom-Oti-Volta Occidental                      0.0
F_Western Oti-Volta                                   0.0
F_Germanic                                            0.0
F_Northwest Germanic                                  0.0
F_West Germanic                                       0.0
F_Franconian                                          0.0
F_High Franconian                                     0.0
F_Cochimi-Yuman                                       0.0
F_Yuman                                               0.0
F_General Yuman                                       0.0
F_Delta-Californian Yuman                             0.0
F_Graeco-Phrygian                                     0.0
F_Greek                                               0.0
F_Attic                                               0.0
F_Koineic Greek                                       0.0
F_North Sea Germanic                                  0.0
F_Anglo-Frisian                                       0.0
F_Anglian                                             0.0
F_Mercian                                             0.0
F_Macro-English                                       0.0
F_Tungusic                                            0.0
F_Northern Tungusic                                   0.0
F_Gbe                                                 0.0
F_Western Gbe                                         0.0
F_Nubian                                              0.0
F_Nobiin Nubian                                       0.0
F_Uralic                                              0.0
F_Finnic                                              0.0
F_Nuclear Finnish                                     0.0
F_Italic                                              0.0
F_Latino-Faliscan                                     0.0
F_Latinic                                             0.0
F_Imperial Latin                                      0.0
F_Romance                                             0.0
F_Italo-Western Romance                               0.0
F_Western Romance                                     0.0
F_Shifted Western Romance                             0.0
F_Northwestern Shifted Romance                        0.0
F_Gallo-Rhaetian                                      0.0
F_Oil                                                 0.0
F_Ga-Dangme                                           0.0
F_Gadsup-Agarabi                                      0.0
F_Gbaya-Manza-Ngbaka                                  0.0
F_Gbaya Meridional-Occidental                         0.0
F_Bokoto-Gbeya                                        0.0
F_Gbeya (Bokoto-Gbeya)                                0.0
F_Gbeya-Suma                                          0.0
F_Goidelic                                            0.0
F_Western Goidelic                                    0.0
F_Brahmaputran                                        0.0
F_Bodo-Garo                                           0.0
F_Guajiro-Paraujano                                   0.0
F_Tupian                                              0.0
F_Tupi-Guarani                                        0.0
F_Tupi-Guarani Subgroup I                             0.0
F_Tupi-Guarani Subgroup I.A                           0.0
F_Paraguay-Brazil Guarani                             0.0
F_South Chinese                                       0.0
F_West Chadic A A.1                                   0.0
F_Central Pacific                                     0.0
F_East Fijian-Polynesian                              0.0
F_Polynesian                                          0.0
F_Nuclear Polynesian                                  0.0
F_Haida                                               0.0
F_Northwest Semitic                                   0.0
F_Canaanite                                           0.0
F_Hebrewic                                            0.0
F_Indo-Aryan Central zone                             0.0
F_Subcontinental Central Indo-Aryan                   0.0
F_Western Hindi                                       0.0
F_Hindustani                                          0.0
F_Uto-Aztecan                                         0.0
F_Northern Uto-Aztecan                                0.0
F_Pacific Coast Athapaskan                            0.0
F_California Athapaskan                               0.0
F_Armenian                                            0.0
F_Eastern-Western Armenian                            0.0
F_Loyalty Islands                                     0.0
F_Igboid                                              0.0
F_Igbo                                                0.0
F_Bolivia-Parana                                      0.0
F_Moxo                                                0.0
F_South Cushitic                                      0.0
F_West Rift South Cushitic                            0.0
F_Northern West Rift South Cushitic                   0.0
F_Iraqw-Gorowa                                        0.0
F_North Germanic                                      0.0
F_West Scandinavian                                   0.0
F_Icelandic-Faroese                                   0.0
F_Hmong-Mien                                          0.0
F_Mienic                                              0.0
F_Mien-Mun                                            0.0
F_Javanesic                                           0.0
F_Modern Javanese                                     0.0
F_Jivaroan                                            0.0
F_Shuaric                                             0.0
F_Japonic                                             0.0
F_Japanese                                            0.0
F_Japan-Taiwan Japanese                               0.0
F_Eskimo                                              0.0
F_Inuit                                               0.0
F_Indo-Aryan Northwestern zone                        0.0
F_Kartvelian                                          0.0
F_Georgian-Zan                                        0.0
F_Georgic                                             0.0
F_Abkhaz-Adyge                                        0.0
F_Circassian                                          0.0
F_Khantyic                                            0.0
F_West Khanty                                         0.0
F_Yeniseian                                           0.0
F_Northern Yeniseian                                  0.0
F_Dravidian                                           0.0
F_South Dravidian                                     0.0
F_South Dravidian I                                   0.0
F_Tamil-Kannada                                       0.0
F_Tamil-Kota                                          0.0
F_Austroasiatic                                       0.0
F_Khasi-Palaung                                       0.0
F_Khasian                                             0.0
F_Khasi-Pnar-Lyngngam                                 0.0
F_Khasi-Pnar                                          0.0
F_Mongolic                                            0.0
F_Eastern Mongolic                                    0.0
F_Oirat-Khalkha                                       0.0
F_Khalkha-Buriat                                      0.0
F_Mongolian                                           0.0
F_Ngero-Vitiaz linkage                                0.0
F_Khmeric                                             0.0
F_Mundaic                                             0.0
F_South Munda                                         0.0
F_Kipchak                                             0.0
F_South Kipchak                                       0.0
F_Paman                                               0.0
F_Southwest Pama                                      0.0
F_Upper Southwest Paman                               0.0
F_Kunjen-Undjan-Athima                                0.0
F_Sepik                                               0.0
F_Nukuma                                              0.0
F_Saharan                                             0.0
F_Western Saharan                                     0.0
F_Kanuri                                              0.0
F_Kanuric                                             0.0
F_Koreanic                                            0.0
F_Permian                                             0.0
F_Komi                                                0.0
F_North Dravidian                                     0.0
F_Kurux-Malto                                         0.0
F_Kurux                                               0.0
F_Karenic                                             0.0
F_Southern Karen                                      0.0
F_Sgaw                                                0.0
F_Goilalan                                            0.0
F_Wakashan                                            0.0
F_Northern Wakashan                                   0.0
F_Kwakiutlan                                          0.0
F_Tai-Kadai                                           0.0
F_Kam-Tai                                             0.0
F_Lakkia-Biao                                         0.0
F_Nakh-Daghestanian                                   0.0
F_Daghestanian                                        0.0
F_Central Sudanic                                     0.0
F_Moru-Madi                                           0.0
F_Central Moru-Madi                                   0.0
F_Burmo-Qiangic                                       0.0
F_Lolo-Burmese                                        0.0
F_Loloish                                             0.0
F_Lahoid                                              0.0
F_Eastern Baltic                                      0.0
F_Siouan                                              0.0
F_Core Siouan                                         0.0
F_Mississippi Valley                                  0.0
F_Dakotan                                             0.0
F_Njila                                               0.0
F_Southern Njila                                      0.0
F_Chokwe-Lunda                                        0.0
F_Chokwe-Luchazi (K.20)                               0.0
F_Chokwe-Lwena                                        0.0
F_Californian Uto-Aztecan                             0.0
F_Cupan                                               0.0
F_Nilotic                                             0.0
F_Western Nilotic                                     0.0
F_Luo-Burun                                           0.0
F_Southern Lwoo                                       0.0
F_Adhola-Alur-Luo                                     0.0
F_Adhola-Luo                                          0.0
F_Otomanguean                                         0.0
F_Eastern Otomanguean                                 0.0
F_Popoloca-Zapotecan                                  0.0
F_Popolocan-Mazatecan                                 0.0
F_Mazatecan                                           0.0
F_Mazatec B                                           0.0
F_Eastern Nilotic                                     0.0
F_Teso-Lotuxo-Maa                                     0.0
F_Lotuxo-Maa                                          0.0
F_Ongamo-Maa                                          0.0